workflows:
  development-workflow:
    name: Development Workflow
    instance_type: mac_mini
    max_build_duration: 60

    environment:
      vars:
          BUNDLE_ID: "com.jetwallet.Jetwallet"
          APP_STORE_ID: 1571266508
          APPLE_ID: Encrypted(Z0FBQUFBQmd3TGZUSDVTOFR5LWRITjJBTm9TbDUwbGdJdGpyN09jdWNFZjVPUGp0SVU2NUJIQTN0LUhNYndGVnhHdk41TTl1aXljT3dOc1ZSTlVobnVFeG9ZN3dIMEEyR2d6Y1VwZnBvWFdGS3hQY0xNWXFDMGs9)
          APPLE_APP_SPECIFIC_PASSWORD: Encrypted(Z0FBQUFBQmd3TG13dm9vWURQcXNMRjgtVGs4UTNSU1h4dXN1cmRTSy1wX3lCRV9aay1sRkthNHZHV1kxZU1iYzRNT1lpS05DWFZMeC1XemxrVzZrZU1IdHdHVGhxSE1Gc3lLY2M0cy1BYVREVG5fZDh1TkdrXzA9)
          APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmd3TVF4Sjg5ZTQwanRkWlkySmQxYlBGOGJ4VU5yT3A5YnNHSjgxVVZLbklueWRXMm9zRGxZQTQzd1RKSUhiRUdIdmtTdXJMVUFPYnFjRkRoaHFCM2pIVDEwaFhpcVI4MzhrS21wUUFteWpiM1IzekZQSWZwdDhnOVhzRlc5Y3dISTk1NEc=)
          APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmd3TVFhNWFWV1loWDkyNlU1cDkxSUlNLV9OQVRSbURVN2o3RndUWkRsdUZSdDlCdXJEUHI3eGx2aFVQNEZNRi13Smw2aEVjS3RERTF3MEdRZ0pSNHdKR1E1REE9PQ==)
          APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmd3TlRJODJzNnUxWEdGcWc3SFhwR3V1OHVzTC1WWXpDeWZlVFZ0N3BMOURVaGJveEVSMEItcG9QXzlteTFXejdDd2Y3M3B5Zm9Sb1dITWgwTERnZWJuN0FuWi1ud3JSb2dMb2J6bjhZYkhsQ0piQzhEMW51OUlKSWhrQ1pJTXZGNTlLclRWcG1QR0lEbE45c1lTM2w2T3hPcUVnbVI3dVVkUnNKSkUyQkFWZHJSQzRVTFREQjZ0RkY5My1Fb0F6d29zODlHak9DWWV0WndmUmdFaldoRlpfVzhid2I2S3Y3bW5yLUVncTAzUUNnT01NdmgteEdwUURSY2F6UlgwY3dBblREOEp1Um1tek9kVm5aRUZmdzRVZFpiMUdvODhISUFEYTgxRlNPV2lXZnd4dmlabjczR05oOE1WMlRTbkJaeW9MMXF0bGtwenJTSGc1UXVDMVd0SlM1LVE2QlpZQ1VlclhFS2NsUXFRTTRrek5QeXhFUm9UZTkyYllJVXhaTVMtRm5pRmNqRWphZTM3bkZGRkhQQzZ5QVduZz09)
          CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmd3Tld4aFFYUzJrb3B4RDNoQk45ZVNnSndaSHpQYTVrZ1B3cTctN3Rkc0F3d01wYVZhMGhxOU1mZ2NOY0ZMTV9FOTF6Y2JsUVhWdWRqdGxsc2JsS25IUlphTVFBejdFcl82UDVRUG50TGNDT1BKdTdyZUhWeXhma3V2RnpseWktQ3RuYTN0VHNIOUhEc2Z4YkxhTWFWRERWVTFHM0RlN3RhZmlEWkhNMVdrNndQdC1mbG1QUTNVcFBjYXhWRlQzTi03aS1jTm4wQW5BQ1VuUXNKcmQ4dzdWZjNjb05jY0FrcG0zbm1WVGliaEhHbmQtQWtYVEhZdnVxamtpLVhzZHExYkhBa2NBQUJmNTVkR2RtREFhZXpEX1BicDB0WXp6cVprWWlEVl9pWENIODZWcmJ5bkkyVldvdS1pR1B3UDBSMVpvSy1lZ3ZCclRBVUNBOWJwTHVuR3hmSUwzU1FHSTc2S2M2VWVFdTl3SGl6RFJYNXFfc1dudlJkNkRqdVowUmd1dXFUVVpSckYzdUVaX2EzdFdQS2k5dUg4MkRVUVNTR3B4OHVjM1Q0d195QlpkM0xuQ2hHSzFFQk8wZWRCRDZOek1zSHhRZVRSdkZERGFFTXl4VGpSZnFSTi03c19rVnJBSDFGMDl2WkdKRTRxRFhsZ0VmZXVGMl9pTlJPQmRjYmJJYXFzdk1VX21MMzhPUUhRV0t4MXZtbHp2cnhSOUlXTmhRRG9meFNnWnBWUlg1d0tOMkVqTXRvNEIwUTFJY0FmdFpLZWNLUTlLeXNwMmZJQXhJd011RnpBTUpGSmdLTHY1Y29kOHdtLXZzd2R3TU9NWi1iUXJUelB6c3NxS2Z6XzEtVS0xZ1p3ZHlacVNDT19SUnpZYlBXVHdEaWR5VVB4UnZ0SVhtNGFpS0pfdE5UYjhmTzNsd2ZLMFJsWndFQ25GTWE4MlpQS2R1SHdiSFdlcXFUT2Q1UktydFpUY0JVVnFoYUZIU1BxTFNCc3BPQWYyZ2ViMXZ6MTlzcXNVTW1WSURrNXNmSnBUeVpsdlZOcWVfdWlPUG94emk1OHJYWDVpMzVYSW5uVF9RNVl1YVZqSWdaSFdoSC1XNG96a0RSUExKcjhuTXo1eVlwd1Y4aG9RNXd4OE9wYUdXMlVnS0U5Q3g1MjVHZHBVZnRmMWVLOEJrbzVKYjBRUW5MbGtFT0VGVlptemNfWmRwNU4wbTkxT1NndWtuaHVGNmpCOHdBeUhHbG9GMXE4RUM1dW9NUGxiYjFYUGk3UnY1aTZGa3F1ZE9iRHV0eHBmTVVEbkJleFdpcDMxZWU0OU5yUE9wX0lrTnlUWktGOUNqeDBqZmdpSm5Va3hfekR5XzFQZ01SMGQ3djcyN1AzakFWMGlZYzJZcjcwV1k4XzFobTRRUTM2MnhkRDhYTTZ1TXM5b1J1eGZPZkZvSWc2cnNFS1JPNy0teTM1azZqQ2dzOXlMa3pWcm5udy1uNy05NkpHOWZqMWU2cUxlOEh2blQ3bktRMnNHOHlGakFYVy12dEpHNWJzbDRxSElLVTdGQ1JjYXdFaFVUanE0RnNpaThhVmtVMTRSbjF3RmhEMEJKY1hQc2VFRXRNVG5wREJ3T3RfQm5lYV95bDNUYUt5Z21sX19NVzcxNFFOS2xrNFp6a1VJbW1PVVlIWUhmTmlDeHZ4cklDMnpYUHMtT0lKV181Wmd2S08zN1JhQmJCUnR3M19wR3BvWVowM2ZLS0xTM3dFU1JqYUVvOG1wclZNUy1ROTlpOWNDZTlISVVMVUp0ZFkxUFRoNENkenlXLUZKVF9VXy15UHZNTXF2ZlBJSkdDdUtyanloNGQ2eHFEMHBGSkJxb3YxdjlXSDZsd29iaHQ0dl9CWnRDcGVyVkZGTS1xRTlJemlqbTJUd3ZCbkE4eGdrS3k4UEZTWkx5eVJCSzU0Q1RMQXFTMlJ3d1Vpb3RHcnhOWlp1VmNaTTZPODFGb0Z5LXpNa3BwWnFuQl9YcUlkTllnb2RIQkNmX0xMMTd2NjgwRVY2QWVvVE9JQnF0S1ZaUGhOZ2FNZ19XSnZYZHBhWFJLLTJKWmtNUVNqVEw0WEhfNTJ1cmk3VXgxZmNpRU9XazJVYmY2MW1oSUx4QVVNTmFEWngwNVdtLWROMEVHRU1CcXZaS2JDczNJY3pLcXVZTGJLRjlzeW9QZkdBdVdzX2ZsWExCRndEdEtXRW5fVi1tV1dxbFhlYTBpcmZRN1Y4dXl1M3VsakFRc3ktSXhyMFNCODFWZkNUeGI1NmVjOFhnSXdITUlLRTZ3NndVS1duWW5uZVpfWTRITFZHeW5na0Y1UDlCVGNRQ1VkR2RTRWw4NF81NklTVmVXYjhYMzcwTDhCeVBpVUhONXNybjloUXBFRW11U3J0dnBUbmFhOS1Nanlrd0NCSGlJUVNnVEVzNEs1WVNaWDI4YVBDSWY0R2h6V0UwMUJhakc5WTlHRnh5Z25ScmcxeTBlOFNuR1pWOHdGM01QNHRvRG9CODZMQmlRQkVzVXZLNlNXcXd5Y2gxUEdNNXA3VkVKV0w0TlpOaDU4QUhLQVlVdDhVaEFWdFRGS0MtVzQydGljQ0FUbjYxSlZqMkVpN2xRRm5FeVhPTFpVQS1LV0NjODdFdWxob25nN3dEcUJWYVZSd0JOM1VReHc4RVUtQ2tsdXlkMEQ4VV9vN2pXc3ZUTkdfaHE4enpJeHdaYmhmbHpCYXBHNmFMT21PdmJZY3VDSldsbG9EWFFqcTg5dWd6XzB4SC0za2NadUhMWkJTdDBpV3ZaVjFHaXBHejE2LWdQNWdSdHNZSkdSdk9rOENiakZGN0FORkl1SUJ1X2FFVm4yZUFibjMyWGs2bW1VcmVPRkk3dkJ6MGhKLVYwU1RzR0dmd1l5MENZUEVQNE91MVd4RkNTcndmbFhDdlEzTk5TOXZTOEJkSWV5Y056ZlVGeDJEdXExcE9wajUzQWZHU001eFlqbmIxaElUNnhjWUt2TTByaGw2dGN4S1ZlM0hTVlhfb3c0SmM4ZWZfeTB6OTBaVmVXclYwYXpKbXR3bThWS0VzX1E3VERtWmVu)

      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.pub-cache

    triggering:
      branch_patterns:
        - pattern: '*'
          include: false
          source: false
      cancel_previous_builds: false

    scripts:
      - name: Set up keychain
        script: keychain initialize
        
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Use system default keychain
        script: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles    

      - name: Get packages
        script: flutter pub get

      - name: Generate autogenerated files
        script: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        script: flutter analyze

      - name: Run tests
        script: flutter test --update-goldens
      
      - name: Build IOS with automatic versioning
        script: |
          flutter clean
          rm -f ios/Podfile.lock pubspec.lock
          rm -rf ios/Pods ios/Runner.xcworkspace
          flutter build ipa --release --build-name=1.0.1 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))  \
          --dart-define=MY_APP_ENV=prod \
          --export-options-plist=/Users/builder/export_options.plist

      - name: Build Android (APK)
        script: flutter build apk

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - flutter_drive.log
    
    publishing:
      app_store_connect:             
          apple_id: $APPLE_ID    
          password: $APPLE_APP_SPECIFIC_PASSWORD

      email:
        recipients:
          - illia.s@smplt.net
        notify:
          success: true
          failure: false
      
      scripts:
        - name: Post-publish script
          script: echo 'Published Successfully!'
