name: jetwallet

packages:
  - apps/**
  - packages/**
  - plugins/**
  - lib/core/**
  - lib/features/**

scripts:
  analyze:
    exec: dart analyze 
  molos bs: flutter pub global run melos bootstrap
  molos clean: flutter pub global run melos clean

bootstrap:
  commands:
    - flutter pub get  