name: jetwallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TOOLKIT
  cupertino_icons: ^1.0.4 # IOS icons
  universal_io: ^2.0.4 # Cross-platform 'dart:io' that works in all platforms
  url_launcher: ^6.0.12 # plugin for launching a URL
  font_awesome_flutter: ^9.2.0 # The Font Awesome Icon pack (1500+ icons)
  pin_code_fields: ^7.3.0 # Generate pin code fields
  qr_flutter: ^4.0.0 # QR code rendering
  grouped_list: ^4.1.0 # List with grouped items
  qr_code_scanner: ^0.6.1 # Scans QR code with camera
  local_auth: ^1.1.8 # local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  intl_phone_number_input: ^0.7.0+2 # phone number in international format that uses Google's libphonenumber
  flutter_svg: ^0.22.0 # SVG rendering and widget library
  contacts_service: ^0.6.3 # contacts fetching
  rive: ^0.7.22 # rive animations
  permission_handler: ^8.3.0 # permissions handling
  percent_indicator: ^3.4.0 # Percent indicator
  auto_size_text: ^3.0.0 # widget that automatically resizes text to fit perfectly within its bounds
  smooth_page_indicator: ^1.0.0+2 # Animated PageView indicators
  timeago: ^3.1.0 # Date converter
  image_picker: ^0.8.4+4 # For selecting images from the Android and iOS image library
  mime_type: ^1.0.0 # MIME type library for Dart HTTP server applications
  decimal: ^2.1.0 # deal with decimal numbers without losing precision
  store_redirect: ^2.0.1 # Redirect to AppStore or GooglePlay

  # RESPONSIVE UI
  device_preview: ^0.7.4
  pixel_perfect: ^1.1.0 # Mock designs

  # PLUS PLUGINS
  # packages without '_plus' was made originally by flutter team are not supported anymore
  # Docs: https://plus.fluttercommunity.dev/docs/overview
  android_intent_plus: ^3.0.2 # plugin for launching Android Intents
  package_info_plus: ^1.3.0 # querying information about the application package
  share_plus: ^3.0.4 # sharing content via the platform share UI
  device_info_plus: ^3.1.1 # providing detailed information about the device

  # NETWORKING:
  dio: ^4.0.1 # http client
  pretty_dio_logger: ^1.1.1 # logger for dio
  signalr_core: ^1.1.1 # ASP.NET Core SignalR Client
  json_annotation: ^4.3.0 # annotations used by json_serializable

  # INTERNATIONALIZATION:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # LOCAL SECURE STORAGE:
  flutter_secure_storage: ^4.2.1

  # STATE MANAGEMENT
  hooks_riverpod: ^0.14.0+5 # riverpod with hooks from Remi Rousselet
  flutter_hooks: ^0.18.0  # additional hooks' functionality

  # FIREBASE
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_dynamic_links: ^3.0.1
  firebase_remote_config: ^0.11.0+2

  # NOTIFICATIONS
  flutter_local_notifications: ^9.1.0

  # OTHER:
  freezed_annotation: ^0.14.3 # Annotations for the freezed
  mocktail: ^0.2.0 # mocking library with null-safety support
  logging: ^1.0.2 # APIs for debugging and error logging
  fast_rsa: ^3.2.0 # RSA signing

  # OWN LIBS:
  simple_kit:
    path: plugins/simple_kit
  charts:
    path: plugins/simple_chart
  simple_analytics:
    path: plugins/simple_analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  # RULES:
  lint: ^1.8.1

  # AUTOGEN:
  freezed: ^0.14.5 # generation for immutable classes that has a simple syntax/API
  build_runner: ^2.1.5 # generating files using Dart code
  json_serializable: ^6.0.1 # dart build system builders for handling JSON

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.otf
          weight: 100

        - asset: assets/fonts/Gilroy-UltraLight.otf
          weight: 200

        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300

        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400

        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500

        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600

        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700

        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/Gilroy-Black.otf
          weight: 900

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/flags/
