name: jetwallet
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TOOLKIT
  cupertino_icons: ^1.0.8 # IOS icons
  universal_io: 2.2.2 # Cross-platform 'dart:io' that works in all platforms
  url_launcher: ^6.3.1 # plugin for launching a URL
  pin_code_fields: 8.0.1 # Generate pin code fields
  qr_flutter: 4.1.0 # QR code rendering
  grouped_list: 6.0.0 # List with grouped items
  flutter_slidable: ^3.1.1
  visibility_detector: ^0.4.0+2
  mobile_scanner: 6.0.2
  local_auth: 2.3.0 # local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  intl_phone_number_input: ^0.7.4 # phone number in international format that uses Google's libphonenumber
  flutter_svg: ^2.0.10+1 # SVG rendering and widget library
  rive: 0.13.15 # rive animations
  permission_handler: 11.3.1 # permissions handling
  auto_size_text: ^3.0.0 # widget that automatically resizes text to fit perfectly within its bounds
  smooth_page_indicator: ^1.2.0+3 # Animated PageView indicators
  timeago: ^3.7.0 # Date converter
  image_picker: ^1.1.2 # For selecting images from the Android and iOS image library
  mime_type: ^1.0.1 # MIME type library for Dart HTTP server applications
  decimal: ^3.0.2 # deal with decimal numbers without losing precision
  store_redirect: 2.0.3 # Redirect to AppStore or GooglePlay
  crisp: # Library for support chart and knowledge base
    git:
      url: https://github.com/cuongtm130996/flutter-crisp.git
  webview_flutter: ^4.10.0 # Library for web view
  webview_flutter_android: ^4.0.0 # Library for configuring web view for ios
  webview_flutter_wkwebview: ^3.16.0 # Library for configuring web view for ios
  appsflyer_sdk: 6.15.2 # plugin for AppsFlyer SDK with Android and iOS support
  credit_card_validator: ^2.1.0 # Credit card validation helpers
  flutter_holo_date_picker: ^2.0.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  event_bus: ^2.0.1
  native_flutter_proxy: ^0.1.15
  http_proxy: ^1.2.2
  animated_list_plus: 0.5.2
  flutter_idensic_mobile_sdk_plugin: 1.33.1
#    path: plugins/flutter_idensic_mobile_sdk_plugin
  mask_text_input_formatter: ^2.9.0
  dynamic_height_grid_view: ^0.0.4
  responsive_grid_list: ^1.4.0
  collection: ^1.18.0
  animated_background: ^2.0.0
  flutter_flip_card: ^0.0.6
  flutter_inappwebview: ^6.1.5
  timezone: ^0.9.4
  readmore: ^3.0.0

  lottie: 3.1.3

  # PLUS PLUGINS
  # packages without '_plus' was made originally by flutter team are not supported anymore
  # Docs: https://plus.fluttercommunity.dev/docs/overview
  android_intent_plus: ^5.2.0 # plugin for launching Android Intents
  package_info_plus: 8.1.0 # querying information about the application package NEED UPDATE
  #  share_plus: 10.0.0
  share_plus: # Custom share_plus (added Intent.FLAG_ACTIVITY_NEW_TASK
    path: plugins/share_plus # sharing content via the platform share UI
  device_info_plus: 11.1.0 # providing detailed information about the device
  connectivity_plus: ^6.1.0 # plugin allows Flutter apps to discover network connectivity
  device_marketing_names: 0.9.3
  android_id: ^0.4.0
  flutter_native_splash: ^2.4.2
  custom_refresh_indicator: ^4.0.1
  isolator: ^2.0.8
  flutter_launcher_icons: ^0.14.1
  in_app_review: ^2.0.9

  # NETWORKING:
  http: 1.2.2
  dio: 5.7.0 # http client
  pretty_dio_logger: 1.4.0 # logger for dio
  signalr_core: # ASP.NET Core SignalR Client
    git:
      url: https://github.com/mtrfnvwork/signalr_core.git
  json_annotation: 4.9.0 # annotations used by json_serializable

  # INTERNATIONALIZATION:
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # LOCAL SECURE STORAGE:
  flutter_secure_storage: 9.2.2

  # STATE MANAGEMENT
  data_channel: 2.0.0+1
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  # SL
  injectable: 2.5.0
  get_it: 8.0.2
  provider: 6.1.2

  # Routing
  auto_route: 9.2.2

  # FIREBASE
  firebase_core: 3.6.0
  firebase_messaging: 15.1.3
  firebase_dynamic_links: 6.0.8
  firebase_crashlytics: 4.1.3
  firebase_analytics: 11.3.3

  # NOTIFICATIONS
  flutter_local_notifications: 17.2.4

  # OTHER:
  sentry_flutter: ^8.9.0 # Debug performance issues and errors
  freezed_annotation: 2.4.4 # Annotations for the freezed
  mocktail: 1.0.4 # mocking library with null-safety support
  logging: 1.3.0 # APIs for debugging and error logging
  uuid: ^4.5.1 # UUID Generator and Parser
  app_tracking_transparency: 2.0.6
  flutter_displaymode: 0.6.0
  open_mail_app: ^0.4.5
  flutter_pdfview: 1.3.4
  confetti: 0.8.0
  logger: ^2.4.0
  dotted_border: ^2.1.0
  intercom_flutter: 9.1.1
  gap: ^3.0.1
  file_picker: ^8.1.3

  # CRYPTOGRAPHY:
  rsa_encrypt: 2.0.0 # RSA encryption
  pointycastle: 3.9.1 # supplementary to rsa_encrypt
  openpgp: 3.8.3 # OpenPGP encryption
  crypto: 3.0.6 # Implementations of SHA, MD5, and HMAC
  encrypt: 5.0.3 # Encryption and decryption helpers

  external_app_launcher: ^4.0.0

  # OWN LIBS:
  simple_kit:
    path: plugins/simple_kit
  simple_networking:
    path: plugins/simple_networking
  simple_analytics:
    path: plugins/simple_analytics
  charts:
    path: plugins/simple_chart
  simple_sift:
    path: plugins/sift
  simple_kit_updated:
    path: plugins/simple_kit_updated

dev_dependencies:
  flutter_test:
    sdk: flutter

  # RULES:
  lint: ^2.3.0

  # AUTOGEN:
  freezed: 2.5.7 # generation for immutable classes that has a simple syntax/API
  build_runner: 2.4.13
  json_serializable: 6.8.0 # dart build system builders for handling JSON
  injectable_generator: 2.6.2
  mobx_codegen: 2.6.2
  auto_route_generator: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.otf
          weight: 100

        - asset: assets/fonts/Gilroy-UltraLight.otf
          weight: 200

        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300

        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400

        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500

        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600

        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700

        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/Gilroy-Black.otf
          weight: 900

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/flags/
    - assets/tvchart/
    - assets/tvchart/public/
    - assets/tvchart/public/bundles/
