name: jetwallet
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TOOLKIT
  cupertino_icons: ^1.0.6 # IOS icons
  universal_io: 2.2.2 # Cross-platform 'dart:io' that works in all platforms
  url_launcher: ^6.2.5 # plugin for launching a URL
  pin_code_fields: 8.0.1 # Generate pin code fields
  qr_flutter: 4.1.0 # QR code rendering
  grouped_list: 5.1.2 # List with grouped items
  flutter_slidable: ^3.0.1
  visibility_detector: ^0.4.0+2
  mobile_scanner: 3.5.7
  local_auth: 2.2.0 # local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  intl_phone_number_input: ^0.7.4 # phone number in international format that uses Google's libphonenumber
  flutter_svg: ^2.0.7 # SVG rendering and widget library
  rive: 0.12.4 # rive animations
  permission_handler: 11.3.0 # permissions handling
  auto_size_text: ^3.0.0 # widget that automatically resizes text to fit perfectly within its bounds
  smooth_page_indicator: ^1.1.0 # Animated PageView indicators
  timeago: ^3.6.1 # Date converter
  image_picker: ^1.0.7 # For selecting images from the Android and iOS image library
  mime_type: ^1.0.0 # MIME type library for Dart HTTP server applications
  decimal: ^2.3.3 # deal with decimal numbers without losing precision
  store_redirect: 2.0.1 # Redirect to AppStore or GooglePlay
  crisp: ^0.3.1 # Library for support chart and knowledge base
  flutter_webview_pro: ^3.0.1+1 # provides a WebView widget on Android and iOS
  appsflyer_sdk: 6.13.0+2 # plugin for AppsFlyer SDK with Android and iOS support
  credit_card_validator: ^2.1.0 # Credit card validation helpers
  flutter_holo_date_picker: ^1.1.3
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  event_bus: ^2.0.0
  native_flutter_proxy: ^0.1.15
  http_proxy: ^1.2.1
  animated_list_plus: 0.5.2
  flutter_idensic_mobile_sdk_plugin: 1.29.0
  mask_text_input_formatter: ^2.9.0
  dynamic_height_grid_view: ^0.0.4
  responsive_grid_list: ^1.4.0
  collection: ^1.18.0
  animated_background: ^2.0.0
  flutter_flip_card: ^0.0.5
  flutter_inappwebview: ^5.3.2
  timezone: ^0.9.2

  lottie: 2.7.0

  # PLUS PLUGINS
  # packages without '_plus' was made originally by flutter team are not supported anymore
  # Docs: https://plus.fluttercommunity.dev/docs/overview
  android_intent_plus: ^4.0.3 # plugin for launching Android Intents
  package_info_plus: 5.0.1 # querying information about the application package NEED UPDATE
  share_plus: 7.2.2 # sharing content via the platform share UI
  device_info_plus: 9.1.2 # providing detailed information about the device
  connectivity_plus: ^2.3.9 # plugin allows Flutter apps to discover network connectivity
  device_marketing_names: 0.8.1
  android_id: ^0.3.6
  flutter_native_splash: ^2.2.17
  custom_refresh_indicator: ^3.0.0
  isolator: ^2.0.8
  flutter_launcher_icons: ^0.13.1
  in_app_review: ^2.0.8

  # NETWORKING:
  http: 0.13.5
  dio: 5.4.1 # http client
  pretty_dio_logger: 1.3.1 # logger for dio
  signalr_core: ^1.1.1 # ASP.NET Core SignalR Client
  json_annotation: 4.8.1 # annotations used by json_serializable

  # INTERNATIONALIZATION:
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # LOCAL SECURE STORAGE:
  flutter_secure_storage: 9.0.0

  # STATE MANAGEMENT
  data_channel: 2.0.0+1
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0

  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5

  # SL
  injectable: 2.3.2
  get_it: 7.6.7
  provider: 6.1.2

  # Routing
  auto_route: 7.8.4

  # FIREBASE
  firebase_core: 2.26.0
  firebase_messaging: 14.7.18
  firebase_dynamic_links: 5.4.16
  firebase_crashlytics: 3.4.17
  firebase_analytics: 10.8.8

  # NOTIFICATIONS
  flutter_local_notifications: 16.3.3

  # OTHER:
  freezed_annotation: 2.4.1 # Annotations for the freezed
  mocktail: 1.0.3 # mocking library with null-safety support
  logging: 1.2.0 # APIs for debugging and error logging
  uuid: ^4.3.3 # UUID Generator and Parser
  app_tracking_transparency: 2.0.4
  flutter_displaymode: 0.6.0
  open_mail_app: ^0.4.5
  flutter_pdfview: 1.3.2
  confetti: 0.7.0
  logger: ^2.1.0
  dotted_border: ^2.1.0
  intercom_flutter: ^9.0.1

  # CRYPTOGRAPHY:
  rsa_encrypt: 2.0.0 # RSA encryption
  pointycastle: 3.7.4 # supplementary to rsa_encrypt
  openpgp: 3.7.2 # OpenPGP encryption
  crypto: 3.0.3 # Implementations of SHA, MD5, and HMAC
  encrypt: 5.0.3 # Encryption and decryption helpers

  external_app_launcher: ^4.0.0

  # OWN LIBS:
  simple_kit:
    path: plugins/simple_kit
  simple_networking:
    path: plugins/simple_networking
  simple_analytics:
    path: plugins/simple_analytics
  charts:
    path: plugins/simple_chart
  simple_sift:
    path: plugins/sift
  simple_kit_updated:
    path: plugins/simple_kit_updated

dev_dependencies:
  flutter_test:
    sdk: flutter

  # RULES:
  lint: ^2.3.0

  # AUTOGEN:
  freezed: 2.4.7 # generation for immutable classes that has a simple syntax/API
  build_runner: 2.4.8
  json_serializable: 6.7.1 # dart build system builders for handling JSON
  injectable_generator: 2.4.1
  mobx_codegen: 2.6.0+1
  auto_route_generator: 7.3.2

dependency_overrides:
  dart_style:
  intl: 0.18.0
  quiver: ^3.2.1

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.otf
          weight: 100

        - asset: assets/fonts/Gilroy-UltraLight.otf
          weight: 200

        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300

        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400

        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500

        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 600

        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700

        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/Gilroy-Black.otf
          weight: 900

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/flags/
    - assets/tvchart/
    - assets/tvchart/public/
    - assets/tvchart/public/bundles/
