class CountriesService {
  CountryModel findCountryByISOCode(String isoCode) {
    return countriesList.firstWhere(
      (element) => element.isoCode == isoCode.toLowerCase(),
    );
  }

  CountryModel findCountryByCurrency(String curr) {
    final index = countriesList.indexWhere(
      (element) => element.currCode == curr.toLowerCase(),
    );

    return index == -1 ? findCountryByISOCode('tg') : countriesList[index];
  }

  List<CountryModel> countriesList = [
    CountryModel('eu', 'eur'),
    CountryModel('us', 'usd'),
    CountryModel('nz', 'nzd'),
    CountryModel('ck', 'nzd'),
    CountryModel('nu', 'nzd'),
    CountryModel('pn', 'nzd'),
    CountryModel('tk', 'nzd'),
    CountryModel('au', 'aud'),
    CountryModel('cx', 'aud'),
    CountryModel('cc', 'aud'),
    CountryModel('hm', 'aud'),
    CountryModel('ki', 'aud'),
    CountryModel('nr', 'aud'),
    CountryModel('nf', 'aud'),
    CountryModel('tv', 'aud'),
    CountryModel('as', 'eur'),
    CountryModel('ad', 'eur'),
    CountryModel('at', 'eur'),
    CountryModel('be', 'eur'),
    CountryModel('fi', 'eur'),
    CountryModel('fr', 'eur'),
    CountryModel('gf', 'eur'),
    CountryModel('tf', 'eur'),
    CountryModel('de', 'eur'),
    CountryModel('gr', 'eur'),
    CountryModel('gp', 'eur'),
    CountryModel('ie', 'eur'),
    CountryModel('it', 'eur'),
    CountryModel('lu', 'eur'),
    CountryModel('mq', 'eur'),
    CountryModel('yt', 'eur'),
    CountryModel('mc', 'eur'),
    CountryModel('nl', 'eur'),
    CountryModel('pt', 'eur'),
    CountryModel('re', 'eur'),
    CountryModel('ws', 'eur'),
    CountryModel('sm', 'eur'),
    CountryModel('si', 'eur'),
    CountryModel('es', 'eur'),
    CountryModel('va', 'eur'),
    CountryModel('gs', 'gbp'),
    CountryModel('gb', 'gbp'),
    CountryModel('je', 'gbp'),
    CountryModel('io', 'usd'),
    CountryModel('gu', 'usd'),
    CountryModel('mh', 'usd'),
    CountryModel('fm', 'usd'),
    CountryModel('mp', 'usd'),
    CountryModel('pw', 'usd'),
    CountryModel('pr', 'usd'),
    CountryModel('tc', 'usd'),
    CountryModel('um', 'usd'),
    CountryModel('vg', 'usd'),
    CountryModel('vi', 'usd'),
    CountryModel('hk', 'hkd'),
    CountryModel('ca', 'cad'),
    CountryModel('jp', 'jpy'),
    CountryModel('af', 'afn'),
    CountryModel('al', 'all'),
    CountryModel('dz', 'dzd'),
    CountryModel('ai', 'xcd'),
    CountryModel('ag', 'xcd'),
    CountryModel('dm', 'xcd'),
    CountryModel('gd', 'xcd'),
    CountryModel('ms', 'xcd'),
    CountryModel('kn', 'xcd'),
    CountryModel('lc', 'xcd'),
    CountryModel('vc', 'xcd'),
    CountryModel('ar', 'ars'),
    CountryModel('am', 'amd'),
    CountryModel('aw', 'ang'),
    CountryModel('an', 'ang'),
    CountryModel('az', 'azn'),
    CountryModel('bs', 'bsd'),
    CountryModel('bh', 'bhd'),
    CountryModel('bd', 'bdt'),
    CountryModel('bb', 'bbd'),
    CountryModel('by', 'byr'),
    CountryModel('bz', 'bzd'),
    CountryModel('bj', 'xof'),
    CountryModel('bf', 'xof'),
    CountryModel('gw', 'xof'),
    CountryModel('ci', 'xof'),
    CountryModel('ml', 'xof'),
    CountryModel('ne', 'xof'),
    CountryModel('sn', 'xof'),
    CountryModel('tg', 'xof'),
    CountryModel('bm', 'bmd'),
    CountryModel('in', 'inr'),
    CountryModel('bt', 'inr'),
    CountryModel('bo', 'bob'),
    CountryModel('bw', 'bwp'),
    CountryModel('bv', 'nok'),
    CountryModel('no', 'nok'),
    CountryModel('sj', 'nok'),
    CountryModel('br', 'brl'),
    CountryModel('bn', 'bnd'),
    CountryModel('bg', 'bgn'),
    CountryModel('bi', 'bif'),
    CountryModel('kh', 'khr'),
    CountryModel('cm', 'xaf'),
    CountryModel('cf', 'xaf'),
    CountryModel('td', 'xaf'),
    CountryModel('cg', 'xaf'),
    CountryModel('gq', 'xaf'),
    CountryModel('ga', 'xaf'),
    CountryModel('cv', 'cve'),
    CountryModel('ky', 'kyd'),
    CountryModel('cl', 'clp'),
    CountryModel('cn', 'cny'),
    CountryModel('co', 'cop'),
    CountryModel('km', 'kmf'),
    CountryModel('cd', 'cdf'),
    CountryModel('cr', 'crc'),
    CountryModel('hr', 'hrk'),
    CountryModel('cu', 'cup'),
    CountryModel('cy', 'cyp'),
    CountryModel('cz', 'czk'),
    CountryModel('dk', 'dkk'),
    CountryModel('fo', 'dkk'),
    CountryModel('gl', 'dkk'),
    CountryModel('dj', 'djf'),
    CountryModel('do', 'dop'),
    CountryModel('id', 'idr'),
    CountryModel('ec', 'ecs'),
    CountryModel('eg', 'egp'),
    CountryModel('sv', 'svc'),
    CountryModel('er', 'etb'),
    CountryModel('et', 'etb'),
    CountryModel('ee', 'eek'),
    CountryModel('fk', 'fkp'),
    CountryModel('fj', 'fjd'),
    CountryModel('pf', 'xpf'),
    CountryModel('nc', 'xpf'),
    CountryModel('wf', 'xpf'),
    CountryModel('gm', 'gmd'),
    CountryModel('ge', 'gel'),
    CountryModel('gi', 'gip'),
    CountryModel('gt', 'gtq'),
    CountryModel('gn', 'gnf'),
    CountryModel('gy', 'gyd'),
    CountryModel('ht', 'htg'),
    CountryModel('hn', 'hnl'),
    CountryModel('hu', 'huf'),
    CountryModel('is', 'isk'),
    CountryModel('ir', 'irr'),
    CountryModel('iq', 'iqd'),
    CountryModel('il', 'ils'),
    CountryModel('jm', 'jmd'),
    CountryModel('jo', 'jod'),
    CountryModel('kz', 'kzt'),
    CountryModel('ke', 'kes'),
    CountryModel('kp', 'kpw'),
    CountryModel('kr', 'krw'),
    CountryModel('kw', 'kwd'),
    CountryModel('kg', 'kgs'),
    CountryModel('la', 'lak'),
    CountryModel('lv', 'lvl'),
    CountryModel('lb', 'lbp'),
    CountryModel('ls', 'lsl'),
    CountryModel('lr', 'lrd'),
    CountryModel('ly', 'lyd'),
    CountryModel('li', 'chf'),
    CountryModel('ch', 'chf'),
    CountryModel('lt', 'ltl'),
    CountryModel('mo', 'mop'),
    CountryModel('mk', 'mkd'),
    CountryModel('mg', 'mga'),
    CountryModel('mw', 'mwk'),
    CountryModel('my', 'myr'),
    CountryModel('mv', 'mvr'),
    CountryModel('mt', 'mtl'),
    CountryModel('mr', 'mro'),
    CountryModel('mu', 'mur'),
    CountryModel('mx', 'mxn'),
    CountryModel('md', 'mdl'),
    CountryModel('mn', 'mnt'),
    CountryModel('ma', 'mad'),
    CountryModel('eh', 'mad'),
    CountryModel('mz', 'mzn'),
    CountryModel('mm', 'mmk'),
    CountryModel('na', 'nad'),
    CountryModel('np', 'npr'),
    CountryModel('ni', 'nio'),
    CountryModel('ng', 'ngn'),
    CountryModel('om', 'omr'),
    CountryModel('pk', 'pkr'),
    CountryModel('pa', 'pab'),
    CountryModel('pg', 'pgk'),
    CountryModel('py', 'pyg'),
    CountryModel('pe', 'pen'),
    CountryModel('ph', 'php'),
    CountryModel('pl', 'pln'),
    CountryModel('qa', 'qar'),
    CountryModel('ro', 'ron'),
    CountryModel('ru', 'rub'),
    CountryModel('rw', 'rwf'),
    CountryModel('st', 'std'),
    CountryModel('sa', 'sar'),
    CountryModel('sc', 'scr'),
    CountryModel('sl', 'sll'),
    CountryModel('sg', 'sgd'),
    CountryModel('sk', 'skk'),
    CountryModel('sb', 'sbd'),
    CountryModel('so', 'sos'),
    CountryModel('za', 'zar'),
    CountryModel('lk', 'lkr'),
    CountryModel('sd', 'sdg'),
    CountryModel('sr', 'srd'),
    CountryModel('sz', 'szl'),
    CountryModel('se', 'sek'),
    CountryModel('sy', 'syp'),
    CountryModel('tw', 'twd'),
    CountryModel('tj', 'tjs'),
    CountryModel('tz', 'tzs'),
    CountryModel('th', 'thb'),
    CountryModel('to', 'top'),
    CountryModel('tt', 'ttd'),
    CountryModel('tn', 'tnd'),
    CountryModel('tr', 'try'),
    CountryModel('tm', 'tmt'),
    CountryModel('ug', 'ugx'),
    CountryModel('ua', 'uah'),
    CountryModel('ae', 'aed'),
    CountryModel('uy', 'uyu'),
    CountryModel('uz', 'uzs'),
    CountryModel('vu', 'vuv'),
    CountryModel('ve', 'vef'),
    CountryModel('vn', 'vnd'),
    CountryModel('ye', 'yer'),
    CountryModel('zm', 'zmk'),
    CountryModel('zw', 'zwd'),
    CountryModel('ax', 'eur'),
    CountryModel('ao', 'aoa'),
    CountryModel('aq', 'aqd'),
    CountryModel('ba', 'bam'),
    CountryModel('cd', 'cdf'),
    CountryModel('gh', 'ghs'),
    CountryModel('gg', 'ggp'),
    CountryModel('im', 'gbp'),
    CountryModel('la', 'lak'),
    CountryModel('mo', 'mop'),
    CountryModel('me', 'eur'),
    CountryModel('ps', 'jod'),
    CountryModel('bl', 'eur'),
    CountryModel('sh', 'gbp'),
    CountryModel('mf', 'ang'),
    CountryModel('pm', 'eur'),
    CountryModel('rs', 'rsd'),
  ];
}

class CountryModel {
  CountryModel(String code, String curr) {
    isoCode = code;
    currCode = curr;
  }

  String isoCode = '';
  String currCode = '';

  String flagAssetName() {
    return 'assets/flags/${isoCode.toLowerCase()}.svg';
  }
}
