import 'simple_number.dart';

const sPhoneNumbers = [
  SPhoneNumber(
    numCode: '',
    countryName: 'Afghanistan',
    countryCode: '+93',
    alphaCode: 'AF',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Åland Islands',
    countryCode: '+358',
    alphaCode: 'AX',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Albania',
    countryCode: '+355',
    alphaCode: 'AL',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Algeria',
    countryCode: '+213',
    alphaCode: 'DZ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'American Samoa',
    countryCode: '+1684',
    alphaCode: 'AS',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Andorra',
    countryCode: '+376',
    alphaCode: 'AD',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Angola',
    countryCode: '+244',
    alphaCode: 'AO',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Anguilla',
    countryCode: '+1264',
    alphaCode: 'AI',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antarctica',
    countryCode: '+672',
    alphaCode: 'AQ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antigua and Barbuda',
    countryCode: '+1268',
    alphaCode: 'AG',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Argentina',
    countryCode: '+54',
    alphaCode: 'AR',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Armenia',
    countryCode: '+374',
    alphaCode: 'AM',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Aruba',
    countryCode: '+297',
    alphaCode: 'AW',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Australia',
    countryCode: '+61',
    alphaCode: 'AU',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Austria',
    countryCode: '+43',
    alphaCode: 'AT',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Azerbaijan',
    countryCode: '+994',
    alphaCode: 'AZ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahamas',
    countryCode: '+1242',
    alphaCode: 'BS',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahrain',
    countryCode: '+973',
    alphaCode: 'BH',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bangladesh',
    countryCode: '+880',
    alphaCode: 'BD',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Barbados',
    countryCode: '+1246',
    alphaCode: 'BB',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belarus',
    countryCode: '+375',
    alphaCode: 'BY',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belgium',
    countryCode: '+32',
    alphaCode: 'BE',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belize',
    countryCode: '+501',
    alphaCode: 'BZ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Benin',
    countryCode: '+229',
    alphaCode: 'BJ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bermuda',
    countryCode: '+1441',
    alphaCode: 'BM',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bhutan',
    countryCode: '+975',
    alphaCode: 'BT',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bolivia',
    countryCode: '+591',
    alphaCode: 'BO',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bosnia and Herzegovina',
    countryCode: '+387',
    alphaCode: 'BA',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Botswana',
    countryCode: '+267',
    alphaCode: 'BW',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bouvet Island',
    countryCode: '+47',
    alphaCode: 'BV',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brazil',
    countryCode: '+55',
    alphaCode: 'BR',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'British Indian Ocean Territory',
    countryCode: '+246',
    alphaCode: 'IO',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brunei Darussalam',
    countryCode: '+673',
    alphaCode: 'BN',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bulgaria',
    countryCode: '+359',
    alphaCode: 'BG',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Burkina Faso',
    countryCode: '+226',
    alphaCode: 'BF',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '108',
    countryName: 'Burundi',
    countryCode: '+257',
    alphaCode: 'BI',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '132',
    countryName: 'Cabo Verde',
    countryCode: '+238',
    alphaCode: 'CV',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '116',
    countryName: 'Cambodia',
    countryCode: '+855',
    alphaCode: 'KH',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '120',
    countryName: 'Cameroon',
    countryCode: '+237',
    alphaCode: 'CM',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '124',
    countryName: 'Canada',
    countryCode: '+1',
    alphaCode: 'CA',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '136',
    countryName: 'Cayman Islands',
    countryCode: '+1345',
    alphaCode: 'KY',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '140',
    countryName: 'Central African Republic',
    countryCode: '+236',
    alphaCode: 'CF',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '148',
    countryName: 'Chad',
    countryCode: '+235',
    alphaCode: 'TD',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '152',
    countryName: 'Chile',
    countryCode: '+56',
    alphaCode: 'CL',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '156',
    countryName: 'China',
    countryCode: '+86',
    alphaCode: 'CN',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '162',
    countryName: 'Christmas Island',
    countryCode: '+61',
    alphaCode: 'CX',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '166',
    countryName: 'Cocos (Keeling) Islands',
    countryCode: '+61',
    alphaCode: 'CC',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '170',
    countryName: 'Colombia',
    countryCode: '+57',
    alphaCode: 'CO',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '174',
    countryName: 'Comoros',
    countryCode: '+269',
    alphaCode: 'KM',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '178',
    countryName: 'Congo (Republic of the)',
    countryCode: '+242',
    alphaCode: 'CG',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '180',
    countryName: 'Congo (Democratic Republic of the)',
    countryCode: '+243',
    alphaCode: 'CD',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '184',
    countryName: 'Cook Islands',
    countryCode: '+682',
    alphaCode: '',
    asset: 'CK',
  ),
  SPhoneNumber(
    numCode: '188',
    countryName: 'Costa Rica',
    countryCode: '+506',
    alphaCode: 'CR',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '384',
    countryName: "Côte d'Ivoire",
    countryCode: '+225',
    alphaCode: 'CI',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '191',
    countryName: 'Croatia',
    countryCode: '+385',
    alphaCode: 'HR',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '192',
    countryName: 'Cuba',
    countryCode: '+53',
    alphaCode: 'CU',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '196',
    countryName: 'Cyprus',
    countryCode: '+357',
    alphaCode: 'CY',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '203',
    countryName: 'Czech Republic',
    countryCode: '+420',
    alphaCode: 'CZ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '208',
    countryName: 'Denmark',
    countryCode: '+45',
    alphaCode: 'DK',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '262',
    countryName: 'Djibouti',
    countryCode: '+253',
    alphaCode: 'DJ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '212',
    countryName: 'Dominica',
    countryCode: '+1767',
    alphaCode: 'DM',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '214',
    countryName: 'Dominican Republic',
    countryCode: '+1',
    alphaCode: 'DO',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '218',
    countryName: 'Ecuador',
    countryCode: '+593',
    alphaCode: 'EC',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '818',
    countryName: 'Egypt',
    countryCode: '+20',
    alphaCode: 'EG',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '222',
    alphaCode: 'SV',
    countryName: 'El Salvador',
    countryCode: '+503',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '226',
    countryName: 'Equatorial Guinea',
    countryCode: '+240',
    alphaCode: 'GQ',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '232',
    alphaCode: 'ER',
    countryName: 'Eritrea',
    countryCode: '+291',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '233',
    alphaCode: 'EE',
    countryName: 'Estonia',
    countryCode: '+372',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '231',
    alphaCode: 'ET',
    countryName: 'Ethiopia',
    countryCode: '+251',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '238',
    alphaCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    countryCode: '+500',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '234',
    alphaCode: 'FO',
    countryName: 'Faroe Islands',
    countryCode: '+298',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '242',
    alphaCode: 'FJ',
    countryName: 'Fiji',
    countryCode: '+679',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '246',
    alphaCode: 'FI',
    countryName: 'Finland',
    countryCode: '+358',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '250',
    alphaCode: 'FR',
    countryName: 'France',
    countryCode: '+33',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '254',
    alphaCode: 'GF',
    countryName: 'French Guiana',
    countryCode: '+594',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '258',
    alphaCode: 'PF',
    countryName: 'French Polynesia',
    countryCode: '+689',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '260',
    alphaCode: 'TF',
    countryName: 'French Southern Territories',
    countryCode: '+262',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '266',
    alphaCode: 'GA',
    countryName: 'Gabon',
    countryCode: '+241',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '270',
    alphaCode: 'GM',
    countryName: 'Gambia',
    countryCode: '+220',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '268',
    alphaCode: 'GE',
    countryName: 'Georgia',
    countryCode: '+995',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '276',
    alphaCode: 'DE',
    countryName: 'Germany',
    countryCode: '+49',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '288',
    alphaCode: 'GH',
    countryName: 'Ghana',
    countryCode: '+233',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '292',
    alphaCode: 'GI',
    countryName: 'Gibraltar',
    countryCode: '+350',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '300',
    alphaCode: 'GR',
    countryName: 'Greece',
    countryCode: '+30',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '304',
    alphaCode: 'GL',
    countryName: 'Greenland',
    countryCode: '+299',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '308',
    alphaCode: 'GD',
    countryName: 'Grenada',
    countryCode: '+1473',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '312',
    alphaCode: 'GP',
    countryName: 'Guadeloupe',
    countryCode: '+590',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '316',
    alphaCode: 'GU',
    countryName: 'Guam',
    countryCode: '+1671',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '320',
    alphaCode: 'GT',
    countryName: 'Guatemala',
    countryCode: '+502',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '831',
    alphaCode: 'GG',
    countryName: 'Guernsey',
    countryCode: '+44',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '324',
    alphaCode: 'GN',
    countryName: 'Guinea',
    countryCode: '+224',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '624',
    alphaCode: 'GW',
    countryName: 'Guinea-Bissau',
    countryCode: '+245',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '328',
    alphaCode: 'GY',
    countryName: 'Guyana',
    countryCode: '+592',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '332',
    alphaCode: 'HT',
    countryName: 'Haiti',
    countryCode: '+509',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '334',
    alphaCode: 'HM',
    countryName: 'Heard Island and McDonald Islands',
    countryCode: '+0',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '336',
    alphaCode: 'VA',
    countryName: 'Vatican City State',
    countryCode: '+379',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '340',
    alphaCode: 'HN',
    countryName: 'Honduras',
    countryCode: '+504',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '344',
    alphaCode: 'HK',
    countryName: 'Hong Kong',
    countryCode: '+852',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '348',
    alphaCode: 'HU',
    countryName: 'Hungary',
    countryCode: '+36',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '352',
    alphaCode: 'IS',
    countryName: 'Iceland',
    countryCode: '+354',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '356',
    alphaCode: 'IN',
    countryName: 'India',
    countryCode: '+91',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '360',
    alphaCode: 'ID',
    countryName: 'Indonesia',
    countryCode: '+62',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '364',
    alphaCode: 'IR',
    countryName: 'Iran',
    countryCode: '+98',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '368',
    alphaCode: 'IQ',
    countryName: 'Iraq',
    countryCode: '+964',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '372',
    alphaCode: 'IE',
    countryName: 'Ireland',
    countryCode: '+353',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '833',
    alphaCode: 'IM',
    countryName: 'Isle of Man',
    countryCode: '+44',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '376',
    alphaCode: 'IL',
    countryName: 'Israel',
    countryCode: '+972',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '380',
    alphaCode: 'IT',
    countryName: 'Italy',
    countryCode: '+39',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '388',
    alphaCode: 'JM',
    countryName: 'Jamaica',
    countryCode: '+1876',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '392',
    alphaCode: 'JP',
    countryName: 'Japan',
    countryCode: '+81',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '832',
    alphaCode: 'JE',
    countryName: 'Jersey',
    countryCode: '+44',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '400',
    alphaCode: 'JO',
    countryName: 'Jordan',
    countryCode: '+962',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '398',
    alphaCode: 'KZ',
    countryName: 'Kazakhstan',
    countryCode: '+7',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '404',
    alphaCode: 'KE',
    countryName: 'Kenya',
    countryCode: '+254',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '296',
    alphaCode: 'KI',
    countryName: 'Kiribati',
    countryCode: '+686',
    asset: '',
  ),

  SPhoneNumber(
    numCode: '408',
    alphaCode: 'KP',
    countryName: "Korea (Democratic People's Republic of)",
    countryCode: '+850',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '410',
    alphaCode: 'KR',
    countryName: 'Korea (Republic of)',
    countryCode: '+82',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '414',
    alphaCode: 'KW',
    countryName: 'Kuwait',
    countryCode: '+965',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '417',
    alphaCode: 'KG',
    countryName: 'Kyrgyzstan',
    countryCode: '+996',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '418',
    alphaCode: 'LA',
    countryName: "Lao People's Democratic Republic",
    countryCode: '+856',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '428',
    alphaCode: 'LV',
    countryName: 'Latvia',
    countryCode: '+371',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '422',
    alphaCode: 'LB',
    countryName: 'Lebanon',
    countryCode: '+961',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '426',
    alphaCode: 'LS',
    countryName: 'Lesotho',
    countryCode: '+266',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '430',
    alphaCode: 'LR',
    countryName: 'Liberia',
    countryCode: '+231',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '434',
    alphaCode: 'LY',
    countryName: 'Libya',
    countryCode: '+218',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '438',
    alphaCode: 'LI',
    countryName: 'Liechtenstein',
    countryCode: '+423',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '440',
    alphaCode: 'LT',
    countryName: 'Lithuania',
    countryCode: '+370',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '442',
    alphaCode: 'LU',
    countryName: 'Luxembourg',
    countryCode: '+352',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '446',
    alphaCode: 'MO',
    countryName: 'Macao',
    countryCode: '+853',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '807',
    alphaCode: 'MK',
    countryName: 'Macedonia (the former Yugoslav Republic of)',
    countryCode: '+389',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '450',
    alphaCode: 'MG',
    countryName: 'Madagascar',
    countryCode: '+261',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '454',
    alphaCode: 'MW',
    countryName: 'Malawi',
    countryCode: '+265',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '458',
    alphaCode: 'MY',
    countryName: 'Malaysia',
    countryCode: '+60',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '462',
    alphaCode: 'MV',
    countryName: 'Maldives',
    countryCode: '+960',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '466',
    alphaCode: 'ML',
    countryName: 'Mali',
    countryCode: '+223',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '470',
    alphaCode: 'MT',
    countryName: 'Malta',
    countryCode: '+356',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '584',
    alphaCode: 'MH',
    countryName: 'Marshall Islands',
    countryCode: '+692',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '474',
    alphaCode: 'MQ',
    countryName: 'Martinique',
    countryCode: '+596',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '478',
    alphaCode: 'MR',
    countryName: 'Mauritania',
    countryCode: '+222',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '480',
    alphaCode: 'MU',
    countryName: 'Mauritius',
    countryCode: '+230',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '175',
    alphaCode: 'YT',
    countryName: 'Mayotte',
    countryCode: '+262',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '484',
    alphaCode: 'MX',
    countryName: 'Mexico',
    countryCode: '+52',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '583',
    alphaCode: 'FM',
    countryName: 'Micronesia (Federated States of)',
    countryCode: '+691',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '498',
    alphaCode: 'MD',
    countryName: 'Moldova (Republic of)',
    countryCode: '+373',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '492',
    alphaCode: 'MC',
    countryName: 'Monaco',
    countryCode: '+377',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '496',
    alphaCode: 'MN',
    countryName: 'Mongolia',
    countryCode: '+976',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '499',
    alphaCode: 'ME',
    countryName: 'Montenegro',
    countryCode: '+382',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '500',
    alphaCode: 'MS',
    countryName: 'Montserrat',
    countryCode: '+1664',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '504',
    alphaCode: 'MA',
    countryName: 'Morocco',
    countryCode: '+212',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '508',
    alphaCode: 'MZ',
    countryName: 'Mozambique',
    countryCode: '+258',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '104',
    alphaCode: 'MM',
    countryName: 'Myanmar',
    countryCode: '+95',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '516',
    alphaCode: 'NA',
    countryName: 'Namibia',
    countryCode: '+264',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '520',
    alphaCode: 'NR',
    countryName: 'Nauru',
    countryCode: '+674',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '524',
    alphaCode: 'NP',
    countryName: 'Nepal',
    countryCode: '+977',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '528',
    alphaCode: 'NL',
    countryName: 'Netherlands',
    countryCode: '+31',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '540',
    alphaCode: 'NC',
    countryName: 'New Caledonia',
    countryCode: '+687',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '554',
    alphaCode: 'NZ',
    countryName: 'New Zealand',
    countryCode: '+64',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '558',
    alphaCode: 'NI',
    countryName: 'Nicaragua',
    countryCode: '+505',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '562',
    alphaCode: 'NE',
    countryName: 'Niger',
    countryCode: '+227',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '566',
    alphaCode: 'NG',
    countryName: 'Nigeria',
    countryCode: '+234',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '570',
    alphaCode: 'NU',
    countryName: 'Niue',
    countryCode: '+683',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '574',
    alphaCode: 'NF',
    countryName: 'Norfolk Island',
    countryCode: '+672',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '580',
    alphaCode: 'MP',
    countryName: 'Northern Mariana Islands',
    countryCode: '+1670',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '578',
    alphaCode: 'NO',
    countryName: 'Norway',
    countryCode: '+47',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '512',
    alphaCode: 'OM',
    countryName: 'Oman',
    countryCode: '+968',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '586',
    alphaCode: 'PK',
    countryName: 'Pakistan',
    countryCode: '+92',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '585',
    alphaCode: 'PW',
    countryName: 'Palau',
    countryCode: '+680',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '275',
    alphaCode: 'PS',
    countryName: 'Palestine, State of',
    countryCode: '+970',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '591',
    alphaCode: 'PA',
    countryName: 'Panama',
    countryCode: '+507',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '598',
    alphaCode: 'PG',
    countryName: 'Papua New Guinea',
    countryCode: '+675',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '600',
    alphaCode: 'PY',
    countryName: 'Paraguay',
    countryCode: '+595',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '604',
    alphaCode: 'PE',
    countryName: 'Peru',
    countryCode: '+51',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '608',
    alphaCode: 'PH',
    countryName: 'Philippines',
    countryCode: '+63',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '612',
    alphaCode: 'PN',
    countryName: 'Pitcairn',
    countryCode: '+64',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '616',
    alphaCode: 'PL',
    countryName: 'Poland',
    countryCode: '+48',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '620',
    alphaCode: 'PT',
    countryName: 'Portugal',
    countryCode: '+351',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '630',
    alphaCode: 'PR',
    countryName: 'Puerto Rico',
    countryCode: '+1939',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '634',
    alphaCode: 'QA',
    countryName: 'Qatar',
    countryCode: '+974',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '638',
    alphaCode: 'RE',
    countryName: 'Réunion',
    countryCode: '+262',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '642',
    alphaCode: 'RO',
    countryName: 'Romania',
    countryCode: '+40',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '643',
    alphaCode: 'RU',
    countryName: 'Russian Federation',
    countryCode: '+7',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '646',
    alphaCode: 'RW',
    countryName: 'Rwanda',
    countryCode: '+250',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '652',
    alphaCode: 'BL',
    countryName: 'Saint Barthélemy',
    countryCode: '+590',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '654',
    alphaCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    countryCode: '+290',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '659',
    alphaCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    countryCode: '+1869',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '662',
    alphaCode: 'LC',
    countryName: 'Saint Lucia',
    countryCode: '+1758',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '663',
    alphaCode: 'MF',
    countryName: 'Saint Martin (French part)',
    countryCode: '+590',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '666',
    alphaCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    countryCode: '+508',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '670',
    alphaCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    countryCode: '+1784',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '882',
    alphaCode: 'WS',
    countryName: 'Samoa',
    countryCode: '+685',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '674',
    alphaCode: 'SM',
    countryName: 'San Marino',
    countryCode: '+378',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '678',
    alphaCode: 'ST',
    countryName: 'Sao Tome and Principe',
    countryCode: '+239',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '682',
    alphaCode: 'SA',
    countryName: 'Saudi Arabia',
    countryCode: '+966',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '686',
    alphaCode: 'SN',
    countryName: 'Senegal',
    countryCode: '+221',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '688',
    alphaCode: 'RS',
    countryName: 'Serbia',
    countryCode: '+381',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '690',
    alphaCode: 'SC',
    countryName: 'Seychelles',
    countryCode: '+248',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '694',
    alphaCode: 'SL',
    countryName: 'Sierra Leone',
    countryCode: '+232',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '702',
    alphaCode: 'SG',
    countryName: 'Singapore',
    countryCode: '+65',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '703',
    alphaCode: 'SK',
    countryName: 'Slovakia',
    countryCode: '+421',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '705',
    alphaCode: 'SI',
    countryName: 'Slovenia',
    countryCode: '+386',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '90',
    alphaCode: 'SB',
    countryName: 'Solomon Islands',
    countryCode: '+677',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '706',
    alphaCode: 'SO',
    countryName: 'Somalia',
    countryCode: '+252',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '710',
    alphaCode: 'ZA',
    countryName: 'South Africa',
    countryCode: '+27',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '239',
    alphaCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    countryCode: '+500',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '728',
    alphaCode: 'SS',
    countryName: 'South Sudan',
    countryCode: '+211',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '724',
    alphaCode: 'ES',
    countryName: 'Spain',
    countryCode: '+34',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '144',
    alphaCode: 'LK',
    countryName: 'Sri Lanka',
    countryCode: '+94',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '729',
    alphaCode: 'SD',
    countryName: 'Sudan',
    countryCode: '+249',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '740',
    alphaCode: 'SR',
    countryName: 'Suriname',
    countryCode: '+597',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '744',
    alphaCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    countryCode: '+47',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '748',
    alphaCode: 'SZ',
    countryName: 'Swaziland',
    countryCode: '+268',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '752',
    alphaCode: 'SE',
    countryName: 'Sweden',
    countryCode: '+46',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '756',
    alphaCode: 'CH',
    countryName: 'Switzerland',
    countryCode: '+41',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '760',
    alphaCode: 'SY',
    countryName: 'Syrian Arab Republic',
    countryCode: '+963',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '158',
    alphaCode: 'TW',
    countryName: 'Taiwan',
    countryCode: '+886',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '762',
    alphaCode: 'TJ',
    countryName: 'Tajikistan',
    countryCode: '+992',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '834',
    alphaCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    countryCode: '+255',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '764',
    alphaCode: 'TH',
    countryName: 'Thailand',
    countryCode: '+66',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '626',
    alphaCode: 'TL',
    countryName: 'Timor-Leste',
    countryCode: '+670',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '768',
    alphaCode: 'TG',
    countryName: 'Togo',
    countryCode: '+228',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '772',
    alphaCode: 'TK',
    countryName: 'Tokelau',
    countryCode: '+690',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '776',
    alphaCode: 'TO',
    countryName: 'Tonga',
    countryCode: '+676',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '780',
    alphaCode: 'TT',
    countryName: 'Trinidad and Tobago',
    countryCode: '+1868',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '788',
    alphaCode: 'TN',
    countryName: 'Tunisia',
    countryCode: '+216',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '792',
    alphaCode: 'TR',
    countryName: 'Turkey',
    countryCode: '+90',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '795',
    alphaCode: 'TM',
    countryName: 'Turkmenistan',
    countryCode: '+993',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '796',
    alphaCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    countryCode: '+1649',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '798',
    alphaCode: 'TV',
    countryName: 'Tuvalu',
    countryCode: '+688',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '800',
    alphaCode: 'UG',
    countryName: 'Uganda',
    countryCode: '+256',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '804',
    alphaCode: 'UA',
    countryName: 'Ukraine',
    countryCode: '+380',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '784',
    alphaCode: 'AE',
    countryName: 'United Arab Emirates',
    countryCode: '+971',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '826',
    alphaCode: 'GB',
    countryName: 'United Kingdom of Great Britain and Northern Ireland',
    countryCode: '+44',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '840',
    alphaCode: 'US',
    countryName: 'United States of America',
    countryCode: '+1',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '858',
    alphaCode: 'UY',
    countryName: 'Uruguay',
    countryCode: '+598',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '860',
    alphaCode: 'UZ',
    countryName: 'Uzbekistan',
    countryCode: '+998',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '548',
    alphaCode: 'VU',
    countryName: 'Vanuatu',
    countryCode: '+678',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '862',
    alphaCode: 'VE',
    countryName: 'Venezuela (Bolivarian Republic of)',
    countryCode: '+58',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '704',
    alphaCode: 'VN',
    countryName: 'Vietnam',
    countryCode: '+84',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '92',
    alphaCode: 'VG',
    countryName: 'Virgin Islands (British)',
    countryCode: '+1284',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '850',
    alphaCode: 'VI',
    countryName: 'Virgin Islands (U.S.)',
    countryCode: '+1340',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '876',
    alphaCode: 'WF',
    countryName: 'Wallis and Futuna',
    countryCode: '+681',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '887',
    alphaCode: 'YE',
    countryName: 'Yemen',
    countryCode: '+967',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '894',
    alphaCode: 'ZM',
    countryName: 'Zambia',
    countryCode: '+260',
    asset: '',
  ),
  SPhoneNumber(
    numCode: '716',
    alphaCode: 'ZW',
    countryName: 'Zimbabwe',
    countryCode: '+263',
    asset: '',
  ),
];
