import 'simple_number.dart';

const sPhoneNumbers = [
  SPhoneNumber(
    numCode: '',
    countryName: 'Afghanistan',
    countryCode: '+93',
    isoCode: 'AF',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Åland Islands',
    countryCode: '+358',
    isoCode: 'AX',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Albania',
    countryCode: '+355',
    isoCode: 'AL',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Algeria',
    countryCode: '+213',
    isoCode: 'DZ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'American Samoa',
    countryCode: '+1684',
    isoCode: 'AS',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Andorra',
    countryCode: '+376',
    isoCode: 'AD',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Angola',
    countryCode: '+244',
    isoCode: 'AO',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Anguilla',
    countryCode: '+1264',
    isoCode: 'AI',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antarctica',
    countryCode: '+672',
    isoCode: 'AQ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antigua and Barbuda',
    countryCode: '+1268',
    isoCode: 'AG',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Argentina',
    countryCode: '+54',
    isoCode: 'AR',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Armenia',
    countryCode: '+374',
    isoCode: 'AM',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Aruba',
    countryCode: '+297',
    isoCode: 'AW',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Australia',
    countryCode: '+61',
    isoCode: 'AU',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Austria',
    countryCode: '+43',
    isoCode: 'AT',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Azerbaijan',
    countryCode: '+994',
    isoCode: 'AZ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahamas',
    countryCode: '+1242',
    isoCode: 'BS',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahrain',
    countryCode: '+973',
    isoCode: 'BH',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bangladesh',
    countryCode: '+880',
    isoCode: 'BD',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Barbados',
    countryCode: '+1246',
    isoCode: 'BB',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belarus',
    countryCode: '+375',
    isoCode: 'BY',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belgium',
    countryCode: '+32',
    isoCode: 'BE',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belize',
    countryCode: '+501',
    isoCode: 'BZ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Benin',
    countryCode: '+229',
    isoCode: 'BJ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bermuda',
    countryCode: '+1441',
    isoCode: 'BM',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bhutan',
    countryCode: '+975',
    isoCode: 'BT',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bolivia',
    countryCode: '+591',
    isoCode: 'BO',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bosnia and Herzegovina',
    countryCode: '+387',
    isoCode: 'BA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Botswana',
    countryCode: '+267',
    isoCode: 'BW',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bouvet Island',
    countryCode: '+47',
    isoCode: 'BV',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brazil',
    countryCode: '+55',
    isoCode: 'BR',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'British Indian Ocean Territory',
    countryCode: '+246',
    isoCode: 'IO',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brunei Darussalam',
    countryCode: '+673',
    isoCode: 'BN',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bulgaria',
    countryCode: '+359',
    isoCode: 'BG',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Burkina Faso',
    countryCode: '+226',
    isoCode: 'BF',
  ),
  SPhoneNumber(
    numCode: '108',
    countryName: 'Burundi',
    countryCode: '+257',
    isoCode: 'BI',
  ),
  SPhoneNumber(
    numCode: '132',
    countryName: 'Cabo Verde',
    countryCode: '+238',
    isoCode: 'CV',
  ),
  SPhoneNumber(
    numCode: '116',
    countryName: 'Cambodia',
    countryCode: '+855',
    isoCode: 'KH',
  ),
  SPhoneNumber(
    numCode: '120',
    countryName: 'Cameroon',
    countryCode: '+237',
    isoCode: 'CM',
  ),
  SPhoneNumber(
    numCode: '124',
    countryName: 'Canada',
    countryCode: '+1',
    isoCode: 'CA',
  ),
  SPhoneNumber(
    numCode: '136',
    countryName: 'Cayman Islands',
    countryCode: '+1345',
    isoCode: 'KY',
  ),
  SPhoneNumber(
    numCode: '140',
    countryName: 'Central African Republic',
    countryCode: '+236',
    isoCode: 'CF',
  ),
  SPhoneNumber(
    numCode: '148',
    countryName: 'Chad',
    countryCode: '+235',
    isoCode: 'TD',
  ),
  SPhoneNumber(
    numCode: '152',
    countryName: 'Chile',
    countryCode: '+56',
    isoCode: 'CL',
  ),
  SPhoneNumber(
    numCode: '156',
    countryName: 'China',
    countryCode: '+86',
    isoCode: 'CN',
  ),
  SPhoneNumber(
    numCode: '162',
    countryName: 'Christmas Island',
    countryCode: '+61',
    isoCode: 'CX',
  ),
  SPhoneNumber(
    numCode: '166',
    countryName: 'Cocos (Keeling) Islands',
    countryCode: '+61',
    isoCode: 'CC',
  ),
  SPhoneNumber(
    numCode: '170',
    countryName: 'Colombia',
    countryCode: '+57',
    isoCode: 'CO',
  ),
  SPhoneNumber(
    numCode: '174',
    countryName: 'Comoros',
    countryCode: '+269',
    isoCode: 'KM',
  ),
  SPhoneNumber(
    numCode: '178',
    countryName: 'Congo (Republic of the)',
    countryCode: '+242',
    isoCode: 'CG',
  ),
  SPhoneNumber(
    numCode: '180',
    countryName: 'Congo (Democratic Republic of the)',
    countryCode: '+243',
    isoCode: 'CD',
  ),
  SPhoneNumber(
    numCode: '184',
    countryName: 'Cook Islands',
    countryCode: '+682',
    isoCode: '',
  ),
  SPhoneNumber(
    numCode: '188',
    countryName: 'Costa Rica',
    countryCode: '+506',
    isoCode: 'CR',
  ),
  SPhoneNumber(
    numCode: '384',
    countryName: "Côte d'Ivoire",
    countryCode: '+225',
    isoCode: 'CI',
  ),
  SPhoneNumber(
    numCode: '191',
    countryName: 'Croatia',
    countryCode: '+385',
    isoCode: 'HR',
  ),
  SPhoneNumber(
    numCode: '192',
    countryName: 'Cuba',
    countryCode: '+53',
    isoCode: 'CU',
  ),
  SPhoneNumber(
    numCode: '196',
    countryName: 'Cyprus',
    countryCode: '+357',
    isoCode: 'CY',
  ),
  SPhoneNumber(
    numCode: '203',
    countryName: 'Czech Republic',
    countryCode: '+420',
    isoCode: 'CZ',
  ),
  SPhoneNumber(
    numCode: '208',
    countryName: 'Denmark',
    countryCode: '+45',
    isoCode: 'DK',
  ),
  SPhoneNumber(
    numCode: '262',
    countryName: 'Djibouti',
    countryCode: '+253',
    isoCode: 'DJ',
  ),
  SPhoneNumber(
    numCode: '212',
    countryName: 'Dominica',
    countryCode: '+1767',
    isoCode: 'DM',
  ),
  SPhoneNumber(
    numCode: '214',
    countryName: 'Dominican Republic',
    countryCode: '+1',
    isoCode: 'DO',
  ),
  SPhoneNumber(
    numCode: '218',
    countryName: 'Ecuador',
    countryCode: '+593',
    isoCode: 'EC',
  ),
  SPhoneNumber(
    numCode: '818',
    countryName: 'Egypt',
    countryCode: '+20',
    isoCode: 'EG',
  ),
  SPhoneNumber(
    numCode: '222',
    isoCode: 'SV',
    countryName: 'El Salvador',
    countryCode: '+503',
  ),
  SPhoneNumber(
    numCode: '226',
    countryName: 'Equatorial Guinea',
    countryCode: '+240',
    isoCode: 'GQ',
  ),
  SPhoneNumber(
    numCode: '232',
    isoCode: 'ER',
    countryName: 'Eritrea',
    countryCode: '+291',
  ),
  SPhoneNumber(
    numCode: '233',
    isoCode: 'EE',
    countryName: 'Estonia',
    countryCode: '+372',
  ),
  SPhoneNumber(
    numCode: '231',
    isoCode: 'ET',
    countryName: 'Ethiopia',
    countryCode: '+251',
  ),
  SPhoneNumber(
    numCode: '238',
    isoCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    countryCode: '+500',
  ),
  SPhoneNumber(
    numCode: '234',
    isoCode: 'FO',
    countryName: 'Faroe Islands',
    countryCode: '+298',
  ),
  SPhoneNumber(
    numCode: '242',
    isoCode: 'FJ',
    countryName: 'Fiji',
    countryCode: '+679',
  ),
  SPhoneNumber(
    numCode: '246',
    isoCode: 'FI',
    countryName: 'Finland',
    countryCode: '+358',
  ),
  SPhoneNumber(
    numCode: '250',
    isoCode: 'FR',
    countryName: 'France',
    countryCode: '+33',
  ),
  SPhoneNumber(
    numCode: '254',
    isoCode: 'GF',
    countryName: 'French Guiana',
    countryCode: '+594',
  ),
  SPhoneNumber(
    numCode: '258',
    isoCode: 'PF',
    countryName: 'French Polynesia',
    countryCode: '+689',
  ),
  SPhoneNumber(
    numCode: '260',
    isoCode: 'TF',
    countryName: 'French Southern Territories',
    countryCode: '+262',
  ),
  SPhoneNumber(
    numCode: '266',
    isoCode: 'GA',
    countryName: 'Gabon',
    countryCode: '+241',
  ),
  SPhoneNumber(
    numCode: '270',
    isoCode: 'GM',
    countryName: 'Gambia',
    countryCode: '+220',
  ),
  SPhoneNumber(
    numCode: '268',
    isoCode: 'GE',
    countryName: 'Georgia',
    countryCode: '+995',
  ),
  SPhoneNumber(
    numCode: '276',
    isoCode: 'DE',
    countryName: 'Germany',
    countryCode: '+49',
  ),
  SPhoneNumber(
    numCode: '288',
    isoCode: 'GH',
    countryName: 'Ghana',
    countryCode: '+233',
  ),
  SPhoneNumber(
    numCode: '292',
    isoCode: 'GI',
    countryName: 'Gibraltar',
    countryCode: '+350',
  ),
  SPhoneNumber(
    numCode: '300',
    isoCode: 'GR',
    countryName: 'Greece',
    countryCode: '+30',
  ),
  SPhoneNumber(
    numCode: '304',
    isoCode: 'GL',
    countryName: 'Greenland',
    countryCode: '+299',
  ),
  SPhoneNumber(
    numCode: '308',
    isoCode: 'GD',
    countryName: 'Grenada',
    countryCode: '+1473',
  ),
  SPhoneNumber(
    numCode: '312',
    isoCode: 'GP',
    countryName: 'Guadeloupe',
    countryCode: '+590',
  ),
  SPhoneNumber(
    numCode: '316',
    isoCode: 'GU',
    countryName: 'Guam',
    countryCode: '+1671',
  ),
  SPhoneNumber(
    numCode: '320',
    isoCode: 'GT',
    countryName: 'Guatemala',
    countryCode: '+502',
  ),
  SPhoneNumber(
    numCode: '831',
    isoCode: 'GG',
    countryName: 'Guernsey',
    countryCode: '+44',
  ),
  SPhoneNumber(
    numCode: '324',
    isoCode: 'GN',
    countryName: 'Guinea',
    countryCode: '+224',
  ),
  SPhoneNumber(
    numCode: '624',
    isoCode: 'GW',
    countryName: 'Guinea-Bissau',
    countryCode: '+245',
  ),
  SPhoneNumber(
    numCode: '328',
    isoCode: 'GY',
    countryName: 'Guyana',
    countryCode: '+592',
  ),
  SPhoneNumber(
    numCode: '332',
    isoCode: 'HT',
    countryName: 'Haiti',
    countryCode: '+509',
  ),
  SPhoneNumber(
    numCode: '334',
    isoCode: 'HM',
    countryName: 'Heard Island and McDonald Islands',
    countryCode: '+0',
  ),
  SPhoneNumber(
    numCode: '336',
    isoCode: 'VA',
    countryName: 'Vatican City State',
    countryCode: '+379',
  ),
  SPhoneNumber(
    numCode: '340',
    isoCode: 'HN',
    countryName: 'Honduras',
    countryCode: '+504',
  ),
  SPhoneNumber(
    numCode: '344',
    isoCode: 'HK',
    countryName: 'Hong Kong',
    countryCode: '+852',
  ),
  SPhoneNumber(
    numCode: '348',
    isoCode: 'HU',
    countryName: 'Hungary',
    countryCode: '+36',
  ),
  SPhoneNumber(
    numCode: '352',
    isoCode: 'IS',
    countryName: 'Iceland',
    countryCode: '+354',
  ),
  SPhoneNumber(
    numCode: '356',
    isoCode: 'IN',
    countryName: 'India',
    countryCode: '+91',
  ),
  SPhoneNumber(
    numCode: '360',
    isoCode: 'ID',
    countryName: 'Indonesia',
    countryCode: '+62',
  ),
  SPhoneNumber(
    numCode: '364',
    isoCode: 'IR',
    countryName: 'Iran',
    countryCode: '+98',
  ),
  SPhoneNumber(
    numCode: '368',
    isoCode: 'IQ',
    countryName: 'Iraq',
    countryCode: '+964',
  ),
  SPhoneNumber(
    numCode: '372',
    isoCode: 'IE',
    countryName: 'Ireland',
    countryCode: '+353',
  ),
  SPhoneNumber(
    numCode: '833',
    isoCode: 'IM',
    countryName: 'Isle of Man',
    countryCode: '+44',
  ),
  SPhoneNumber(
    numCode: '376',
    isoCode: 'IL',
    countryName: 'Israel',
    countryCode: '+972',
  ),
  SPhoneNumber(
    numCode: '380',
    isoCode: 'IT',
    countryName: 'Italy',
    countryCode: '+39',
  ),
  SPhoneNumber(
    numCode: '388',
    isoCode: 'JM',
    countryName: 'Jamaica',
    countryCode: '+1876',
  ),
  SPhoneNumber(
    numCode: '392',
    isoCode: 'JP',
    countryName: 'Japan',
    countryCode: '+81',
  ),
  SPhoneNumber(
    numCode: '832',
    isoCode: 'JE',
    countryName: 'Jersey',
    countryCode: '+44',
  ),
  SPhoneNumber(
    numCode: '400',
    isoCode: 'JO',
    countryName: 'Jordan',
    countryCode: '+962',
  ),
  SPhoneNumber(
    numCode: '398',
    isoCode: 'KZ',
    countryName: 'Kazakhstan',
    countryCode: '+7',
  ),
  SPhoneNumber(
    numCode: '404',
    isoCode: 'KE',
    countryName: 'Kenya',
    countryCode: '+254',
  ),
  SPhoneNumber(
    numCode: '296',
    isoCode: 'KI',
    countryName: 'Kiribati',
    countryCode: '+686',
  ),

  SPhoneNumber(
    numCode: '408',
    isoCode: 'KP',
    countryName: "Korea (Democratic People's Republic of)",
    countryCode: '+850',
  ),
  SPhoneNumber(
    numCode: '410',
    isoCode: 'KR',
    countryName: 'Korea (Republic of)',
    countryCode: '+82',
  ),
  SPhoneNumber(
    numCode: '414',
    isoCode: 'KW',
    countryName: 'Kuwait',
    countryCode: '+965',
  ),
  SPhoneNumber(
    numCode: '417',
    isoCode: 'KG',
    countryName: 'Kyrgyzstan',
    countryCode: '+996',
  ),
  SPhoneNumber(
    numCode: '418',
    isoCode: 'LA',
    countryName: "Lao People's Democratic Republic",
    countryCode: '+856',
  ),
  SPhoneNumber(
    numCode: '428',
    isoCode: 'LV',
    countryName: 'Latvia',
    countryCode: '+371',
  ),
  SPhoneNumber(
    numCode: '422',
    isoCode: 'LB',
    countryName: 'Lebanon',
    countryCode: '+961',
  ),
  SPhoneNumber(
    numCode: '426',
    isoCode: 'LS',
    countryName: 'Lesotho',
    countryCode: '+266',
  ),
  SPhoneNumber(
    numCode: '430',
    isoCode: 'LR',
    countryName: 'Liberia',
    countryCode: '+231',
  ),
  SPhoneNumber(
    numCode: '434',
    isoCode: 'LY',
    countryName: 'Libya',
    countryCode: '+218',
  ),
  SPhoneNumber(
    numCode: '438',
    isoCode: 'LI',
    countryName: 'Liechtenstein',
    countryCode: '+423',
  ),
  SPhoneNumber(
    numCode: '440',
    isoCode: 'LT',
    countryName: 'Lithuania',
    countryCode: '+370',
  ),
  SPhoneNumber(
    numCode: '442',
    isoCode: 'LU',
    countryName: 'Luxembourg',
    countryCode: '+352',
  ),
  SPhoneNumber(
    numCode: '446',
    isoCode: 'MO',
    countryName: 'Macao',
    countryCode: '+853',
  ),
  SPhoneNumber(
    numCode: '807',
    isoCode: 'MK',
    countryName: 'Macedonia (the former Yugoslav Republic of)',
    countryCode: '+389',
  ),
  SPhoneNumber(
    numCode: '450',
    isoCode: 'MG',
    countryName: 'Madagascar',
    countryCode: '+261',
  ),
  SPhoneNumber(
    numCode: '454',
    isoCode: 'MW',
    countryName: 'Malawi',
    countryCode: '+265',
  ),
  SPhoneNumber(
    numCode: '458',
    isoCode: 'MY',
    countryName: 'Malaysia',
    countryCode: '+60',
  ),
  SPhoneNumber(
    numCode: '462',
    isoCode: 'MV',
    countryName: 'Maldives',
    countryCode: '+960',
  ),
  SPhoneNumber(
    numCode: '466',
    isoCode: 'ML',
    countryName: 'Mali',
    countryCode: '+223',
  ),
  SPhoneNumber(
    numCode: '470',
    isoCode: 'MT',
    countryName: 'Malta',
    countryCode: '+356',
  ),
  SPhoneNumber(
    numCode: '584',
    isoCode: 'MH',
    countryName: 'Marshall Islands',
    countryCode: '+692',
  ),
  SPhoneNumber(
    numCode: '474',
    isoCode: 'MQ',
    countryName: 'Martinique',
    countryCode: '+596',
  ),
  SPhoneNumber(
    numCode: '478',
    isoCode: 'MR',
    countryName: 'Mauritania',
    countryCode: '+222',
  ),
  SPhoneNumber(
    numCode: '480',
    isoCode: 'MU',
    countryName: 'Mauritius',
    countryCode: '+230',
  ),
  SPhoneNumber(
    numCode: '175',
    isoCode: 'YT',
    countryName: 'Mayotte',
    countryCode: '+262',
  ),
  SPhoneNumber(
    numCode: '484',
    isoCode: 'MX',
    countryName: 'Mexico',
    countryCode: '+52',
  ),
  SPhoneNumber(
    numCode: '583',
    isoCode: 'FM',
    countryName: 'Micronesia (Federated States of)',
    countryCode: '+691',
  ),
  SPhoneNumber(
    numCode: '498',
    isoCode: 'MD',
    countryName: 'Moldova (Republic of)',
    countryCode: '+373',
  ),
  SPhoneNumber(
    numCode: '492',
    isoCode: 'MC',
    countryName: 'Monaco',
    countryCode: '+377',
  ),
  SPhoneNumber(
    numCode: '496',
    isoCode: 'MN',
    countryName: 'Mongolia',
    countryCode: '+976',
  ),
  SPhoneNumber(
    numCode: '499',
    isoCode: 'ME',
    countryName: 'Montenegro',
    countryCode: '+382',
  ),
  SPhoneNumber(
    numCode: '500',
    isoCode: 'MS',
    countryName: 'Montserrat',
    countryCode: '+1664',
  ),
  SPhoneNumber(
    numCode: '504',
    isoCode: 'MA',
    countryName: 'Morocco',
    countryCode: '+212',
  ),
  SPhoneNumber(
    numCode: '508',
    isoCode: 'MZ',
    countryName: 'Mozambique',
    countryCode: '+258',
  ),
  SPhoneNumber(
    numCode: '104',
    isoCode: 'MM',
    countryName: 'Myanmar',
    countryCode: '+95',
  ),
  SPhoneNumber(
    numCode: '516',
    isoCode: 'NA',
    countryName: 'Namibia',
    countryCode: '+264',
  ),
  SPhoneNumber(
    numCode: '520',
    isoCode: 'NR',
    countryName: 'Nauru',
    countryCode: '+674',
  ),
  SPhoneNumber(
    numCode: '524',
    isoCode: 'NP',
    countryName: 'Nepal',
    countryCode: '+977',
  ),
  SPhoneNumber(
    numCode: '528',
    isoCode: 'NL',
    countryName: 'Netherlands',
    countryCode: '+31',
  ),
  SPhoneNumber(
    numCode: '540',
    isoCode: 'NC',
    countryName: 'New Caledonia',
    countryCode: '+687',
  ),
  SPhoneNumber(
    numCode: '554',
    isoCode: 'NZ',
    countryName: 'New Zealand',
    countryCode: '+64',
  ),
  SPhoneNumber(
    numCode: '558',
    isoCode: 'NI',
    countryName: 'Nicaragua',
    countryCode: '+505',
  ),
  SPhoneNumber(
    numCode: '562',
    isoCode: 'NE',
    countryName: 'Niger',
    countryCode: '+227',
  ),
  SPhoneNumber(
    numCode: '566',
    isoCode: 'NG',
    countryName: 'Nigeria',
    countryCode: '+234',
  ),
  SPhoneNumber(
    numCode: '570',
    isoCode: 'NU',
    countryName: 'Niue',
    countryCode: '+683',
  ),
  SPhoneNumber(
    numCode: '574',
    isoCode: 'NF',
    countryName: 'Norfolk Island',
    countryCode: '+672',
  ),
  SPhoneNumber(
    numCode: '580',
    isoCode: 'MP',
    countryName: 'Northern Mariana Islands',
    countryCode: '+1670',
  ),
  SPhoneNumber(
    numCode: '578',
    isoCode: 'NO',
    countryName: 'Norway',
    countryCode: '+47',
  ),
  SPhoneNumber(
    numCode: '512',
    isoCode: 'OM',
    countryName: 'Oman',
    countryCode: '+968',
  ),
  SPhoneNumber(
    numCode: '586',
    isoCode: 'PK',
    countryName: 'Pakistan',
    countryCode: '+92',
  ),
  SPhoneNumber(
    numCode: '585',
    isoCode: 'PW',
    countryName: 'Palau',
    countryCode: '+680',
  ),
  SPhoneNumber(
    numCode: '275',
    isoCode: 'PS',
    countryName: 'Palestine, State of',
    countryCode: '+970',
  ),
  SPhoneNumber(
    numCode: '591',
    isoCode: 'PA',
    countryName: 'Panama',
    countryCode: '+507',
  ),
  SPhoneNumber(
    numCode: '598',
    isoCode: 'PG',
    countryName: 'Papua New Guinea',
    countryCode: '+675',
  ),
  SPhoneNumber(
    numCode: '600',
    isoCode: 'PY',
    countryName: 'Paraguay',
    countryCode: '+595',
  ),
  SPhoneNumber(
    numCode: '604',
    isoCode: 'PE',
    countryName: 'Peru',
    countryCode: '+51',
  ),
  SPhoneNumber(
    numCode: '608',
    isoCode: 'PH',
    countryName: 'Philippines',
    countryCode: '+63',
  ),
  SPhoneNumber(
    numCode: '612',
    isoCode: 'PN',
    countryName: 'Pitcairn',
    countryCode: '+64',

  ),
  SPhoneNumber(
    numCode: '616',
    isoCode: 'PL',
    countryName: 'Poland',
    countryCode: '+48',

  ),
  SPhoneNumber(
    numCode: '620',
    isoCode: 'PT',
    countryName: 'Portugal',
    countryCode: '+351',
  ),
  SPhoneNumber(
    numCode: '630',
    isoCode: 'PR',
    countryName: 'Puerto Rico',
    countryCode: '+1939',
  ),
  SPhoneNumber(
    numCode: '634',
    isoCode: 'QA',
    countryName: 'Qatar',
    countryCode: '+974',
  ),
  SPhoneNumber(
    numCode: '638',
    isoCode: 'RE',
    countryName: 'Réunion',
    countryCode: '+262',
  ),
  SPhoneNumber(
    numCode: '642',
    isoCode: 'RO',
    countryName: 'Romania',
    countryCode: '+40',
  ),
  SPhoneNumber(
    numCode: '643',
    isoCode: 'RU',
    countryName: 'Russian Federation',
    countryCode: '+7',
  ),
  SPhoneNumber(
    numCode: '646',
    isoCode: 'RW',
    countryName: 'Rwanda',
    countryCode: '+250',
  ),
  SPhoneNumber(
    numCode: '652',
    isoCode: 'BL',
    countryName: 'Saint Barthélemy',
    countryCode: '+590',
  ),
  SPhoneNumber(
    numCode: '654',
    isoCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    countryCode: '+290',
  ),
  SPhoneNumber(
    numCode: '659',
    isoCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    countryCode: '+1869',
  ),
  SPhoneNumber(
    numCode: '662',
    isoCode: 'LC',
    countryName: 'Saint Lucia',
    countryCode: '+1758',
  ),
  SPhoneNumber(
    numCode: '663',
    isoCode: 'MF',
    countryName: 'Saint Martin (French part)',
    countryCode: '+590',
  ),
  SPhoneNumber(
    numCode: '666',
    isoCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    countryCode: '+508',
  ),
  SPhoneNumber(
    numCode: '670',
    isoCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    countryCode: '+1784',
  ),
  SPhoneNumber(
    numCode: '882',
    isoCode: 'WS',
    countryName: 'Samoa',
    countryCode: '+685',
  ),
  SPhoneNumber(
    numCode: '674',
    isoCode: 'SM',
    countryName: 'San Marino',
    countryCode: '+378',
  ),
  SPhoneNumber(
    numCode: '678',
    isoCode: 'ST',
    countryName: 'Sao Tome and Principe',
    countryCode: '+239',
  ),
  SPhoneNumber(
    numCode: '682',
    isoCode: 'SA',
    countryName: 'Saudi Arabia',
    countryCode: '+966',
  ),
  SPhoneNumber(
    numCode: '686',
    isoCode: 'SN',
    countryName: 'Senegal',
    countryCode: '+221',
  ),
  SPhoneNumber(
    numCode: '688',
    isoCode: 'RS',
    countryName: 'Serbia',
    countryCode: '+381',
  ),
  SPhoneNumber(
    numCode: '690',
    isoCode: 'SC',
    countryName: 'Seychelles',
    countryCode: '+248',
  ),
  SPhoneNumber(
    numCode: '694',
    isoCode: 'SL',
    countryName: 'Sierra Leone',
    countryCode: '+232',
  ),
  SPhoneNumber(
    numCode: '702',
    isoCode: 'SG',
    countryName: 'Singapore',
    countryCode: '+65',
  ),
  SPhoneNumber(
    numCode: '703',
    isoCode: 'SK',
    countryName: 'Slovakia',
    countryCode: '+421',
  ),
  SPhoneNumber(
    numCode: '705',
    isoCode: 'SI',
    countryName: 'Slovenia',
    countryCode: '+386',
  ),
  SPhoneNumber(
    numCode: '90',
    isoCode: 'SB',
    countryName: 'Solomon Islands',
    countryCode: '+677',
  ),
  SPhoneNumber(
    numCode: '706',
    isoCode: 'SO',
    countryName: 'Somalia',
    countryCode: '+252',
  ),
  SPhoneNumber(
    numCode: '710',
    isoCode: 'ZA',
    countryName: 'South Africa',
    countryCode: '+27',
  ),
  SPhoneNumber(
    numCode: '239',
    isoCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    countryCode: '+500',
  ),
  SPhoneNumber(
    numCode: '728',
    isoCode: 'SS',
    countryName: 'South Sudan',
    countryCode: '+211',
  ),
  SPhoneNumber(
    numCode: '724',
    isoCode: 'ES',
    countryName: 'Spain',
    countryCode: '+34',
  ),
  SPhoneNumber(
    numCode: '144',
    isoCode: 'LK',
    countryName: 'Sri Lanka',
    countryCode: '+94',
  ),
  SPhoneNumber(
    numCode: '729',
    isoCode: 'SD',
    countryName: 'Sudan',
    countryCode: '+249',
  ),
  SPhoneNumber(
    numCode: '740',
    isoCode: 'SR',
    countryName: 'Suriname',
    countryCode: '+597',
  ),
  SPhoneNumber(
    numCode: '744',
    isoCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    countryCode: '+47',
  ),
  SPhoneNumber(
    numCode: '748',
    isoCode: 'SZ',
    countryName: 'Swaziland',
    countryCode: '+268',
  ),
  SPhoneNumber(
    numCode: '752',
    isoCode: 'SE',
    countryName: 'Sweden',
    countryCode: '+46',
  ),
  SPhoneNumber(
    numCode: '756',
    isoCode: 'CH',
    countryName: 'Switzerland',
    countryCode: '+41',
  ),
  SPhoneNumber(
    numCode: '760',
    isoCode: 'SY',
    countryName: 'Syrian Arab Republic',
    countryCode: '+963',
  ),
  SPhoneNumber(
    numCode: '158',
    isoCode: 'TW',
    countryName: 'Taiwan',
    countryCode: '+886',
  ),
  SPhoneNumber(
    numCode: '762',
    isoCode: 'TJ',
    countryName: 'Tajikistan',
    countryCode: '+992',
  ),
  SPhoneNumber(
    numCode: '834',
    isoCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    countryCode: '+255',
  ),
  SPhoneNumber(
    numCode: '764',
    isoCode: 'TH',
    countryName: 'Thailand',
    countryCode: '+66',
  ),
  SPhoneNumber(
    numCode: '626',
    isoCode: 'TL',
    countryName: 'Timor-Leste',
    countryCode: '+670',
  ),
  SPhoneNumber(
    numCode: '768',
    isoCode: 'TG',
    countryName: 'Togo',
    countryCode: '+228',
  ),
  SPhoneNumber(
    numCode: '772',
    isoCode: 'TK',
    countryName: 'Tokelau',
    countryCode: '+690',
  ),
  SPhoneNumber(
    numCode: '776',
    isoCode: 'TO',
    countryName: 'Tonga',
    countryCode: '+676',
  ),
  SPhoneNumber(
    numCode: '780',
    isoCode: 'TT',
    countryName: 'Trinidad and Tobago',
    countryCode: '+1868',
  ),
  SPhoneNumber(
    numCode: '788',
    isoCode: 'TN',
    countryName: 'Tunisia',
    countryCode: '+216',
  ),
  SPhoneNumber(
    numCode: '792',
    isoCode: 'TR',
    countryName: 'Turkey',
    countryCode: '+90',
  ),
  SPhoneNumber(
    numCode: '795',
    isoCode: 'TM',
    countryName: 'Turkmenistan',
    countryCode: '+993',
  ),
  SPhoneNumber(
    numCode: '796',
    isoCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    countryCode: '+1649',
  ),
  SPhoneNumber(
    numCode: '798',
    isoCode: 'TV',
    countryName: 'Tuvalu',
    countryCode: '+688',
  ),
  SPhoneNumber(
    numCode: '800',
    isoCode: 'UG',
    countryName: 'Uganda',
    countryCode: '+256',
  ),
  SPhoneNumber(
    numCode: '804',
    isoCode: 'UA',
    countryName: 'Ukraine',
    countryCode: '+380',
  ),
  SPhoneNumber(
    numCode: '784',
    isoCode: 'AE',
    countryName: 'United Arab Emirates',
    countryCode: '+971',
  ),
  SPhoneNumber(
    numCode: '826',
    isoCode: 'GB',
    countryName: 'United Kingdom of Great Britain and Northern Ireland',
    countryCode: '+44',
  ),
  SPhoneNumber(
    numCode: '840',
    isoCode: 'US',
    countryName: 'United States of America',
    countryCode: '+1',
  ),
  SPhoneNumber(
    numCode: '858',
    isoCode: 'UY',
    countryName: 'Uruguay',
    countryCode: '+598',
  ),
  SPhoneNumber(
    numCode: '860',
    isoCode: 'UZ',
    countryName: 'Uzbekistan',
    countryCode: '+998',
  ),
  SPhoneNumber(
    numCode: '548',
    isoCode: 'VU',
    countryName: 'Vanuatu',
    countryCode: '+678',
  ),
  SPhoneNumber(
    numCode: '862',
    isoCode: 'VE',
    countryName: 'Venezuela (Bolivarian Republic of)',
    countryCode: '+58',
  ),
  SPhoneNumber(
    numCode: '704',
    isoCode: 'VN',
    countryName: 'Vietnam',
    countryCode: '+84',
  ),
  SPhoneNumber(
    numCode: '92',
    isoCode: 'VG',
    countryName: 'Virgin Islands (British)',
    countryCode: '+1284',
  ),
  SPhoneNumber(
    numCode: '850',
    isoCode: 'VI',
    countryName: 'Virgin Islands (U.S.)',
    countryCode: '+1340',
  ),
  SPhoneNumber(
    numCode: '876',
    isoCode: 'WF',
    countryName: 'Wallis and Futuna',
    countryCode: '+681',
  ),
  SPhoneNumber(
    numCode: '887',
    isoCode: 'YE',
    countryName: 'Yemen',
    countryCode: '+967',
  ),
  SPhoneNumber(
    numCode: '894',
    isoCode: 'ZM',
    countryName: 'Zambia',
    countryCode: '+260',
  ),
  SPhoneNumber(
    numCode: '716',
    isoCode: 'ZW',
    countryName: 'Zimbabwe',
    countryCode: '+263',
  ),
];
