import 'simple_number.dart';

const sPhoneNumbers = [
  SPhoneNumber(
    numCode: '',
    countryName: 'Afghanistan',
    countryCode: '+93',
    isoCode: 'AF',
    alphaCode: 'AFG',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Åland Islands',
    countryCode: '+358',
    isoCode: 'AX',
    alphaCode: 'ALA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Albania',
    countryCode: '+355',
    isoCode: 'AL',
    alphaCode: 'ALB',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Algeria',
    countryCode: '+213',
    isoCode: 'DZ',
    alphaCode: 'DZA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'American Samoa',
    countryCode: '+1684',
    isoCode: 'AS',
    alphaCode: 'ASM',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Andorra',
    countryCode: '+376',
    isoCode: 'AD',
    alphaCode: 'AND',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Angola',
    countryCode: '+244',
    isoCode: 'AO',
    alphaCode: 'AGO',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Anguilla',
    countryCode: '+1264',
    isoCode: 'AI',
    alphaCode: 'AIA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antarctica',
    countryCode: '+672',
    isoCode: 'AQ',
    alphaCode: 'ATA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Antigua and Barbuda',
    countryCode: '+1268',
    isoCode: 'AG',
    alphaCode: 'ATG',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Argentina',
    countryCode: '+54',
    isoCode: 'AR',
    alphaCode: 'ARG',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Armenia',
    countryCode: '+374',
    isoCode: 'AM',
    alphaCode: 'ARM',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Aruba',
    countryCode: '+297',
    isoCode: 'AW',
    alphaCode: 'ABW',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Australia',
    countryCode: '+61',
    isoCode: 'AU',
    alphaCode: 'AUS',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Austria',
    countryCode: '+43',
    isoCode: 'AT',
    alphaCode: 'AUT',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Azerbaijan',
    countryCode: '+994',
    isoCode: 'AZ',
    alphaCode: 'AZE',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahamas',
    countryCode: '+1242',
    isoCode: 'BS',
    alphaCode: 'BHS',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bahrain',
    countryCode: '+973',
    isoCode: 'BH',
    alphaCode: 'BHR',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bangladesh',
    countryCode: '+880',
    isoCode: 'BD',
    alphaCode: 'BGD',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Barbados',
    countryCode: '+1246',
    isoCode: 'BB',
    alphaCode: 'BRB',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belarus',
    countryCode: '+375',
    isoCode: 'BY',
    alphaCode: 'BLR',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belgium',
    countryCode: '+32',
    isoCode: 'BE',
    alphaCode: 'BEL',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Belize',
    countryCode: '+501',
    isoCode: 'BZ',
    alphaCode: 'BLZ',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Benin',
    countryCode: '+229',
    isoCode: 'BJ',
    alphaCode: 'BEN',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bermuda',
    countryCode: '+1441',
    isoCode: 'BM',
    alphaCode: 'BMU',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bhutan',
    countryCode: '+975',
    isoCode: 'BT',
    alphaCode: 'BTN',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bolivia',
    countryCode: '+591',
    isoCode: 'BO',
    alphaCode: 'BOL',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bosnia and Herzegovina',
    countryCode: '+387',
    isoCode: 'BA',
    alphaCode: 'BIH',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Botswana',
    countryCode: '+267',
    isoCode: 'BW',
    alphaCode: 'BWA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bouvet Island',
    countryCode: '+47',
    isoCode: 'BV',
    alphaCode: 'BVT',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brazil',
    countryCode: '+55',
    isoCode: 'BR',
    alphaCode: 'BRA',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'British Indian Ocean Territory',
    countryCode: '+246',
    isoCode: 'IO',
    alphaCode: 'IOT',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Brunei Darussalam',
    countryCode: '+673',
    isoCode: 'BN',
    alphaCode: 'BRN',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Bulgaria',
    countryCode: '+359',
    isoCode: 'BG',
    alphaCode: 'BGR',
  ),
  SPhoneNumber(
    numCode: '',
    countryName: 'Burkina Faso',
    countryCode: '+226',
    isoCode: 'BF',
    alphaCode: 'BFA',
  ),
  SPhoneNumber(
    numCode: '108',
    countryName: 'Burundi',
    countryCode: '+257',
    isoCode: 'BI',
    alphaCode: 'BDI',
  ),
  SPhoneNumber(
    numCode: '132',
    countryName: 'Cabo Verde',
    countryCode: '+238',
    isoCode: 'CV',
    alphaCode: 'CPV',
  ),
  SPhoneNumber(
    numCode: '116',
    countryName: 'Cambodia',
    countryCode: '+855',
    isoCode: 'KH',
    alphaCode: 'KHM',
  ),
  SPhoneNumber(
    numCode: '120',
    countryName: 'Cameroon',
    countryCode: '+237',
    isoCode: 'CM',
    alphaCode: 'CMR',
  ),
  SPhoneNumber(
    numCode: '124',
    countryName: 'Canada',
    countryCode: '+1',
    isoCode: 'CA',
    alphaCode: 'CAN',
  ),
  SPhoneNumber(
    numCode: '599',
    isoCode: 'BQ',
    countryName: 'Caribbean Netherlands',
    countryCode: '+31',
    alphaCode: 'BQ',
  ),
  SPhoneNumber(
    numCode: '136',
    countryName: 'Cayman Islands',
    countryCode: '+1345',
    isoCode: 'KY',
    alphaCode: 'CYM',
  ),
  SPhoneNumber(
    numCode: '140',
    countryName: 'Central African Republic',
    countryCode: '+236',
    isoCode: 'CF',
    alphaCode: 'CAF',
  ),
  SPhoneNumber(
    numCode: '148',
    countryName: 'Chad',
    countryCode: '+235',
    isoCode: 'TD',
    alphaCode: 'TCD',
  ),
  SPhoneNumber(
    numCode: '152',
    countryName: 'Chile',
    countryCode: '+56',
    isoCode: 'CL',
    alphaCode: 'CHL',
  ),
  SPhoneNumber(
    numCode: '156',
    countryName: 'China',
    countryCode: '+86',
    isoCode: 'CN',
    alphaCode: 'CHN',
  ),
  SPhoneNumber(
    numCode: '162',
    countryName: 'Christmas Island',
    countryCode: '+61',
    isoCode: 'CX',
    alphaCode: 'CXR',
  ),
  SPhoneNumber(
    numCode: '166',
    countryName: 'Cocos (Keeling) Islands',
    countryCode: '+61',
    isoCode: 'CC',
    alphaCode: 'CCK',
  ),
  SPhoneNumber(
    numCode: '170',
    countryName: 'Colombia',
    countryCode: '+57',
    isoCode: 'CO',
    alphaCode: 'COL',
  ),
  SPhoneNumber(
    numCode: '174',
    countryName: 'Comoros',
    countryCode: '+269',
    isoCode: 'KM',
    alphaCode: 'COM',
  ),
  SPhoneNumber(
    numCode: '178',
    countryName: 'Congo (Republic of the)',
    countryCode: '+242',
    isoCode: 'CG',
    alphaCode: 'COG',
  ),
  SPhoneNumber(
    numCode: '180',
    countryName: 'Congo (Democratic Republic of the)',
    countryCode: '+243',
    isoCode: 'CD',
    alphaCode: 'COD',
  ),
  SPhoneNumber(
    numCode: '184',
    countryName: 'Cook Islands',
    countryCode: '+682',
    isoCode: 'CK',
    alphaCode: 'COK',
  ),
  SPhoneNumber(
    numCode: '188',
    countryName: 'Costa Rica',
    countryCode: '+506',
    isoCode: 'CR',
    alphaCode: 'CRI',
  ),
  SPhoneNumber(
    numCode: '384',
    countryName: "Côte d'Ivoire",
    countryCode: '+225',
    isoCode: 'CI',
    alphaCode: 'CIV',
  ),
  SPhoneNumber(
    numCode: '191',
    countryName: 'Croatia',
    countryCode: '+385',
    isoCode: 'HR',
    alphaCode: 'HRV',
  ),
  SPhoneNumber(
    numCode: '192',
    countryName: 'Cuba',
    countryCode: '+53',
    isoCode: 'CU',
    alphaCode: 'CUB',
  ),
  SPhoneNumber(
    numCode: '599',
    isoCode: 'CW',
    countryName: 'Curacao',
    countryCode: '+599',
    alphaCode: 'CW',
  ),
  SPhoneNumber(
    numCode: '196',
    countryName: 'Cyprus',
    countryCode: '+357',
    isoCode: 'CY',
    alphaCode: 'CYP',
  ),
  SPhoneNumber(
    numCode: '203',
    countryName: 'Czech Republic',
    countryCode: '+420',
    isoCode: 'CZ',
    alphaCode: 'CZE',
  ),
  SPhoneNumber(
    numCode: '208',
    countryName: 'Denmark',
    countryCode: '+45',
    isoCode: 'DK',
    alphaCode: 'DNK',
  ),
  SPhoneNumber(
    numCode: '262',
    countryName: 'Djibouti',
    countryCode: '+253',
    isoCode: 'DJ',
    alphaCode: 'DJI',
  ),
  SPhoneNumber(
    numCode: '212',
    countryName: 'Dominica',
    countryCode: '+1767',
    isoCode: 'DM',
    alphaCode: 'DMA',
  ),
  SPhoneNumber(
    numCode: '214',
    countryName: 'Dominican Republic',
    countryCode: '+1',
    isoCode: 'DO',
    alphaCode: 'DOM',
  ),
  SPhoneNumber(
    numCode: '218',
    countryName: 'Ecuador',
    countryCode: '+593',
    isoCode: 'EC',
    alphaCode: 'ECU',
  ),
  SPhoneNumber(
    numCode: '818',
    countryName: 'Egypt',
    countryCode: '+20',
    isoCode: 'EG',
    alphaCode: 'EGY',
  ),
  SPhoneNumber(
    numCode: '222',
    isoCode: 'SV',
    countryName: 'El Salvador',
    countryCode: '+503',
    alphaCode: 'SLV',
  ),
  SPhoneNumber(
    numCode: '226',
    countryName: 'Equatorial Guinea',
    countryCode: '+240',
    isoCode: 'GQ',
    alphaCode: 'GNQ',
  ),
  SPhoneNumber(
    numCode: '232',
    isoCode: 'ER',
    countryName: 'Eritrea',
    countryCode: '+291',
    alphaCode: 'ERI',
  ),
  SPhoneNumber(
    numCode: '233',
    isoCode: 'EE',
    countryName: 'Estonia',
    countryCode: '+372',
    alphaCode: 'EST',
  ),
  SPhoneNumber(
    numCode: '231',
    isoCode: 'ET',
    countryName: 'Ethiopia',
    countryCode: '+251',
    alphaCode: 'ETH',
  ),
  SPhoneNumber(
    numCode: '238',
    isoCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    countryCode: '+500',
    alphaCode: 'FLK',
  ),
  SPhoneNumber(
    numCode: '234',
    isoCode: 'FO',
    countryName: 'Faroe Islands',
    countryCode: '+298',
    alphaCode: 'FRO',
  ),
  SPhoneNumber(
    numCode: '242',
    isoCode: 'FJ',
    countryName: 'Fiji',
    countryCode: '+679',
    alphaCode: 'FJI',
  ),
  SPhoneNumber(
    numCode: '246',
    isoCode: 'FI',
    countryName: 'Finland',
    countryCode: '+358',
    alphaCode: 'FIN',
  ),
  SPhoneNumber(
    numCode: '250',
    isoCode: 'FR',
    countryName: 'France',
    countryCode: '+33',
    alphaCode: 'FRA',
  ),
  SPhoneNumber(
    numCode: '254',
    isoCode: 'GF',
    countryName: 'French Guiana',
    countryCode: '+594',
    alphaCode: 'GUF',
  ),
  SPhoneNumber(
    numCode: '258',
    isoCode: 'PF',
    countryName: 'French Polynesia',
    countryCode: '+689',
    alphaCode: 'PYF',
  ),
  SPhoneNumber(
    numCode: '260',
    isoCode: 'TF',
    countryName: 'French Southern Territories',
    countryCode: '+262',
    alphaCode: 'ATF',
  ),
  SPhoneNumber(
    numCode: '266',
    isoCode: 'GA',
    countryName: 'Gabon',
    countryCode: '+241',
    alphaCode: 'GAB',
  ),
  SPhoneNumber(
    numCode: '270',
    isoCode: 'GM',
    countryName: 'Gambia',
    countryCode: '+220',
    alphaCode: 'GMB',
  ),
  SPhoneNumber(
    numCode: '268',
    isoCode: 'GE',
    countryName: 'Georgia',
    countryCode: '+995',
    alphaCode: 'GEO',
  ),
  SPhoneNumber(
    numCode: '276',
    isoCode: 'DE',
    countryName: 'Germany',
    countryCode: '+49',
    alphaCode: 'DEU',
  ),
  SPhoneNumber(
    numCode: '288',
    isoCode: 'GH',
    countryName: 'Ghana',
    countryCode: '+233',
    alphaCode: 'GHA',
  ),
  SPhoneNumber(
    numCode: '292',
    isoCode: 'GI',
    countryName: 'Gibraltar',
    countryCode: '+350',
    alphaCode: 'GIB',
  ),
  SPhoneNumber(
    numCode: '300',
    isoCode: 'GR',
    countryName: 'Greece',
    countryCode: '+30',
    alphaCode: 'GRC',
  ),
  SPhoneNumber(
    numCode: '304',
    isoCode: 'GL',
    countryName: 'Greenland',
    countryCode: '+299',
    alphaCode: 'GRL',
  ),
  SPhoneNumber(
    numCode: '308',
    isoCode: 'GD',
    countryName: 'Grenada',
    countryCode: '+1473',
    alphaCode: 'GRD',
  ),
  SPhoneNumber(
    numCode: '312',
    isoCode: 'GP',
    countryName: 'Guadeloupe',
    countryCode: '+590',
    alphaCode: 'GLP',
  ),
  SPhoneNumber(
    numCode: '316',
    isoCode: 'GU',
    countryName: 'Guam',
    countryCode: '+1671',
    alphaCode: 'GUM',
  ),
  SPhoneNumber(
    numCode: '320',
    isoCode: 'GT',
    countryName: 'Guatemala',
    countryCode: '+502',
    alphaCode: 'GTM',
  ),
  SPhoneNumber(
    numCode: '831',
    isoCode: 'GG',
    countryName: 'Guernsey',
    countryCode: '+44',
    alphaCode: 'GGY',
  ),
  SPhoneNumber(
    numCode: '324',
    isoCode: 'GN',
    countryName: 'Guinea',
    countryCode: '+224',
    alphaCode: 'GIN',
  ),
  SPhoneNumber(
    numCode: '624',
    isoCode: 'GW',
    countryName: 'Guinea-Bissau',
    countryCode: '+245',
    alphaCode: 'GNB',
  ),
  SPhoneNumber(
    numCode: '328',
    isoCode: 'GY',
    countryName: 'Guyana',
    countryCode: '+592',
    alphaCode: 'GUY',
  ),
  SPhoneNumber(
    numCode: '332',
    isoCode: 'HT',
    countryName: 'Haiti',
    countryCode: '+509',
    alphaCode: 'HTI',
  ),
  SPhoneNumber(
    numCode: '334',
    isoCode: 'HM',
    countryName: 'Heard Island and McDonald Islands',
    countryCode: '+0',
    alphaCode: 'HMD',
  ),
  SPhoneNumber(
    numCode: '336',
    isoCode: 'VA',
    countryName: 'Vatican City State',
    countryCode: '+379',
    alphaCode: 'VAT',
  ),
  SPhoneNumber(
    numCode: '340',
    isoCode: 'HN',
    countryName: 'Honduras',
    countryCode: '+504',
    alphaCode: 'HND',
  ),
  SPhoneNumber(
    numCode: '344',
    isoCode: 'HK',
    countryName: 'Hong Kong',
    countryCode: '+852',
    alphaCode: 'HKG',
  ),
  SPhoneNumber(
    numCode: '348',
    isoCode: 'HU',
    countryName: 'Hungary',
    countryCode: '+36',
    alphaCode: 'HUN',
  ),
  SPhoneNumber(
    numCode: '352',
    isoCode: 'IS',
    countryName: 'Iceland',
    countryCode: '+354',
    alphaCode: 'ISL',
  ),
  SPhoneNumber(
    numCode: '356',
    isoCode: 'IN',
    countryName: 'India',
    countryCode: '+91',
    alphaCode: 'IND',
  ),
  SPhoneNumber(
    numCode: '360',
    isoCode: 'ID',
    countryName: 'Indonesia',
    countryCode: '+62',
    alphaCode: 'IDN',
  ),
  SPhoneNumber(
    numCode: '364',
    isoCode: 'IR',
    countryName: 'Iran',
    countryCode: '+98',
    alphaCode: 'IRN',
  ),
  SPhoneNumber(
    numCode: '368',
    isoCode: 'IQ',
    countryName: 'Iraq',
    countryCode: '+964',
    alphaCode: 'IRQ',
  ),
  SPhoneNumber(
    numCode: '372',
    isoCode: 'IE',
    countryName: 'Ireland',
    countryCode: '+353',
    alphaCode: 'IRL',
  ),
  SPhoneNumber(
    numCode: '833',
    isoCode: 'IM',
    countryName: 'Isle of Man',
    countryCode: '+44',
    alphaCode: 'IMN',
  ),
  SPhoneNumber(
    numCode: '376',
    isoCode: 'IL',
    countryName: 'Israel',
    countryCode: '+972',
    alphaCode: 'ISR',
  ),
  SPhoneNumber(
    numCode: '380',
    isoCode: 'IT',
    countryName: 'Italy',
    countryCode: '+39',
    alphaCode: 'ITA',
  ),
  SPhoneNumber(
    numCode: '388',
    isoCode: 'JM',
    countryName: 'Jamaica',
    countryCode: '+1876',
    alphaCode: 'JAM',
  ),
  SPhoneNumber(
    numCode: '392',
    isoCode: 'JP',
    countryName: 'Japan',
    countryCode: '+81',
    alphaCode: 'JPN',
  ),
  SPhoneNumber(
    numCode: '832',
    isoCode: 'JE',
    countryName: 'Jersey',
    countryCode: '+44',
    alphaCode: 'JEY',
  ),
  SPhoneNumber(
    numCode: '400',
    isoCode: 'JO',
    countryName: 'Jordan',
    countryCode: '+962',
    alphaCode: 'JOR',
  ),
  SPhoneNumber(
    numCode: '398',
    isoCode: 'KZ',
    countryName: 'Kazakhstan',
    countryCode: '+7',
    alphaCode: 'KAZ',
  ),
  SPhoneNumber(
    numCode: '404',
    isoCode: 'KE',
    countryName: 'Kenya',
    countryCode: '+254',
    alphaCode: 'KEN',
  ),
  SPhoneNumber(
    numCode: '296',
    isoCode: 'KI',
    countryName: 'Kiribati',
    countryCode: '+686',
    alphaCode: 'KIR',
  ),
  SPhoneNumber(
    numCode: '408',
    isoCode: 'KP',
    countryName: "Korea (Democratic People's Republic of)",
    countryCode: '+850',
    alphaCode: 'PRK',
  ),
  SPhoneNumber(
    numCode: '410',
    isoCode: 'KR',
    countryName: 'Korea (Republic of)',
    countryCode: '+82',
    alphaCode: 'KOR',
  ),
  SPhoneNumber(
    numCode: '414',
    isoCode: 'KW',
    countryName: 'Kuwait',
    countryCode: '+965',
    alphaCode: 'KWT',
  ),
  SPhoneNumber(
    numCode: '417',
    isoCode: 'KG',
    countryName: 'Kyrgyzstan',
    countryCode: '+996',
    alphaCode: 'KGZ',
  ),
  SPhoneNumber(
    numCode: '418',
    isoCode: 'LA',
    countryName: "Lao People's Democratic Republic",
    countryCode: '+856',
    alphaCode: 'LAO',
  ),
  SPhoneNumber(
    numCode: '428',
    isoCode: 'LV',
    countryName: 'Latvia',
    countryCode: '+371',
    alphaCode: 'LVA',
  ),
  SPhoneNumber(
    numCode: '422',
    isoCode: 'LB',
    countryName: 'Lebanon',
    countryCode: '+961',
    alphaCode: 'LBN',
  ),
  SPhoneNumber(
    numCode: '426',
    isoCode: 'LS',
    countryName: 'Lesotho',
    countryCode: '+266',
    alphaCode: 'LSO',
  ),
  SPhoneNumber(
    numCode: '430',
    isoCode: 'LR',
    countryName: 'Liberia',
    countryCode: '+231',
    alphaCode: 'LBR',
  ),
  SPhoneNumber(
    numCode: '434',
    isoCode: 'LY',
    countryName: 'Libya',
    countryCode: '+218',
    alphaCode: 'LBY',
  ),
  SPhoneNumber(
    numCode: '438',
    isoCode: 'LI',
    countryName: 'Liechtenstein',
    countryCode: '+423',
    alphaCode: 'LIE',
  ),
  SPhoneNumber(
    numCode: '440',
    isoCode: 'LT',
    countryName: 'Lithuania',
    countryCode: '+370',
    alphaCode: 'LTU',
  ),
  SPhoneNumber(
    numCode: '442',
    isoCode: 'LU',
    countryName: 'Luxembourg',
    countryCode: '+352',
    alphaCode: 'LUX',
  ),
  SPhoneNumber(
    numCode: '446',
    isoCode: 'MO',
    countryName: 'Macao',
    countryCode: '+853',
    alphaCode: 'MAC',
  ),
  SPhoneNumber(
    numCode: '807',
    isoCode: 'MK',
    countryName: 'Macedonia (the former Yugoslav Republic of)',
    countryCode: '+389',
    alphaCode: 'MKD',
  ),
  SPhoneNumber(
    numCode: '450',
    isoCode: 'MG',
    countryName: 'Madagascar',
    countryCode: '+261',
    alphaCode: 'MDG',
  ),
  SPhoneNumber(
    numCode: '454',
    isoCode: 'MW',
    countryName: 'Malawi',
    countryCode: '+265',
    alphaCode: 'MWI',
  ),
  SPhoneNumber(
    numCode: '458',
    isoCode: 'MY',
    countryName: 'Malaysia',
    countryCode: '+60',
    alphaCode: 'MYS',
  ),
  SPhoneNumber(
    numCode: '462',
    isoCode: 'MV',
    countryName: 'Maldives',
    countryCode: '+960',
    alphaCode: 'MDV',
  ),
  SPhoneNumber(
    numCode: '466',
    isoCode: 'ML',
    countryName: 'Mali',
    countryCode: '+223',
    alphaCode: 'MLI',
  ),
  SPhoneNumber(
    numCode: '470',
    isoCode: 'MT',
    countryName: 'Malta',
    countryCode: '+356',
    alphaCode: 'MLT',
  ),
  SPhoneNumber(
    numCode: '584',
    isoCode: 'MH',
    countryName: 'Marshall Islands',
    countryCode: '+692',
    alphaCode: 'MHL',
  ),
  SPhoneNumber(
    numCode: '474',
    isoCode: 'MQ',
    countryName: 'Martinique',
    countryCode: '+596',
    alphaCode: 'MTQ',
  ),
  SPhoneNumber(
    numCode: '478',
    isoCode: 'MR',
    countryName: 'Mauritania',
    countryCode: '+222',
    alphaCode: 'MRT',
  ),
  SPhoneNumber(
    numCode: '480',
    isoCode: 'MU',
    countryName: 'Mauritius',
    countryCode: '+230',
    alphaCode: 'MUS',
  ),
  SPhoneNumber(
    numCode: '175',
    isoCode: 'YT',
    countryName: 'Mayotte',
    countryCode: '+262',
    alphaCode: 'MYT',
  ),
  SPhoneNumber(
    numCode: '484',
    isoCode: 'MX',
    countryName: 'Mexico',
    countryCode: '+52',
    alphaCode: 'MEX',
  ),
  SPhoneNumber(
    numCode: '583',
    isoCode: 'FM',
    countryName: 'Micronesia (Federated States of)',
    countryCode: '+691',
    alphaCode: 'FSM',
  ),
  SPhoneNumber(
    numCode: '498',
    isoCode: 'MD',
    countryName: 'Moldova (Republic of)',
    countryCode: '+373',
    alphaCode: 'MDA',
  ),
  SPhoneNumber(
    numCode: '492',
    isoCode: 'MC',
    countryName: 'Monaco',
    countryCode: '+377',
    alphaCode: 'MCO',
  ),
  SPhoneNumber(
    numCode: '496',
    isoCode: 'MN',
    countryName: 'Mongolia',
    countryCode: '+976',
    alphaCode: 'MNG',
  ),
  SPhoneNumber(
    numCode: '499',
    isoCode: 'ME',
    countryName: 'Montenegro',
    countryCode: '+382',
    alphaCode: 'MNE',
  ),
  SPhoneNumber(
    numCode: '500',
    isoCode: 'MS',
    countryName: 'Montserrat',
    countryCode: '+1664',
    alphaCode: 'MSR',
  ),
  SPhoneNumber(
    numCode: '504',
    isoCode: 'MA',
    countryName: 'Morocco',
    countryCode: '+212',
    alphaCode: 'MAR',
  ),
  SPhoneNumber(
    numCode: '508',
    isoCode: 'MZ',
    countryName: 'Mozambique',
    countryCode: '+258',
    alphaCode: 'MOZ',
  ),
  SPhoneNumber(
    numCode: '104',
    isoCode: 'MM',
    countryName: 'Myanmar',
    countryCode: '+95',
    alphaCode: 'MMR',
  ),
  SPhoneNumber(
    numCode: '516',
    isoCode: 'NA',
    countryName: 'Namibia',
    countryCode: '+264',
    alphaCode: 'NAM',
  ),
  SPhoneNumber(
    numCode: '520',
    isoCode: 'NR',
    countryName: 'Nauru',
    countryCode: '+674',
    alphaCode: 'NRU',
  ),
  SPhoneNumber(
    numCode: '524',
    isoCode: 'NP',
    countryName: 'Nepal',
    countryCode: '+977',
    alphaCode: 'NPL',
  ),
  SPhoneNumber(
    numCode: '528',
    isoCode: 'NL',
    countryName: 'Netherlands',
    countryCode: '+31',
    alphaCode: 'NLD',
  ),
  SPhoneNumber(
    numCode: '540',
    isoCode: 'NC',
    countryName: 'New Caledonia',
    countryCode: '+687',
    alphaCode: 'NCL',
  ),
  SPhoneNumber(
    numCode: '554',
    isoCode: 'NZ',
    countryName: 'New Zealand',
    countryCode: '+64',
    alphaCode: 'NZL',
  ),
  SPhoneNumber(
    numCode: '558',
    isoCode: 'NI',
    countryName: 'Nicaragua',
    countryCode: '+505',
    alphaCode: 'NIC',
  ),
  SPhoneNumber(
    numCode: '562',
    isoCode: 'NE',
    countryName: 'Niger',
    countryCode: '+227',
    alphaCode: 'NER',
  ),
  SPhoneNumber(
    numCode: '566',
    isoCode: 'NG',
    countryName: 'Nigeria',
    countryCode: '+234',
    alphaCode: 'NGA',
  ),
  SPhoneNumber(
    numCode: '570',
    isoCode: 'NU',
    countryName: 'Niue',
    countryCode: '+683',
    alphaCode: 'NIU',
  ),
  SPhoneNumber(
    numCode: '574',
    isoCode: 'NF',
    countryName: 'Norfolk Island',
    countryCode: '+672',
    alphaCode: 'NFK',
  ),
  SPhoneNumber(
    numCode: '580',
    isoCode: 'MP',
    countryName: 'Northern Mariana Islands',
    countryCode: '+1670',
    alphaCode: 'MNP',
  ),
  SPhoneNumber(
    numCode: '578',
    isoCode: 'NO',
    countryName: 'Norway',
    countryCode: '+47',
    alphaCode: 'NOR',
  ),
  SPhoneNumber(
    numCode: '512',
    isoCode: 'OM',
    countryName: 'Oman',
    countryCode: '+968',
    alphaCode: 'OMN',
  ),
  SPhoneNumber(
    numCode: '586',
    isoCode: 'PK',
    countryName: 'Pakistan',
    countryCode: '+92',
    alphaCode: 'PAK',
  ),
  SPhoneNumber(
    numCode: '585',
    isoCode: 'PW',
    countryName: 'Palau',
    countryCode: '+680',
    alphaCode: 'PLW',
  ),
  SPhoneNumber(
    numCode: '275',
    isoCode: 'PS',
    countryName: 'Palestine, State of',
    countryCode: '+970',
    alphaCode: 'PSE',
  ),
  SPhoneNumber(
    numCode: '591',
    isoCode: 'PA',
    countryName: 'Panama',
    countryCode: '+507',
    alphaCode: 'PAN',
  ),
  SPhoneNumber(
    numCode: '598',
    isoCode: 'PG',
    countryName: 'Papua New Guinea',
    countryCode: '+675',
    alphaCode: 'PNG',
  ),
  SPhoneNumber(
    numCode: '600',
    isoCode: 'PY',
    countryName: 'Paraguay',
    countryCode: '+595',
    alphaCode: 'PRY',
  ),
  SPhoneNumber(
    numCode: '604',
    isoCode: 'PE',
    countryName: 'Peru',
    countryCode: '+51',
    alphaCode: 'PER',
  ),
  SPhoneNumber(
    numCode: '608',
    isoCode: 'PH',
    countryName: 'Philippines',
    countryCode: '+63',
    alphaCode: 'PHL',
  ),
  SPhoneNumber(
    numCode: '612',
    isoCode: 'PN',
    countryName: 'Pitcairn',
    countryCode: '+64',
    alphaCode: 'PCN',
  ),
  SPhoneNumber(
    numCode: '616',
    isoCode: 'PL',
    countryName: 'Poland',
    countryCode: '+48',
    alphaCode: 'POL',
  ),
  SPhoneNumber(
    numCode: '620',
    isoCode: 'PT',
    countryName: 'Portugal',
    countryCode: '+351',
    alphaCode: 'PRT',
  ),
  SPhoneNumber(
    numCode: '630',
    isoCode: 'PR',
    countryName: 'Puerto Rico',
    countryCode: '+1939',
    alphaCode: 'PRI',
  ),
  SPhoneNumber(
    numCode: '634',
    isoCode: 'QA',
    countryName: 'Qatar',
    countryCode: '+974',
    alphaCode: 'QAT',
  ),
  SPhoneNumber(
    numCode: '638',
    isoCode: 'RE',
    countryName: 'Réunion',
    countryCode: '+262',
    alphaCode: 'REU',
  ),
  SPhoneNumber(
    numCode: '642',
    isoCode: 'RO',
    countryName: 'Romania',
    countryCode: '+40',
    alphaCode: 'ROU',
  ),
  SPhoneNumber(
    numCode: '643',
    isoCode: 'RU',
    countryName: 'Russian Federation',
    countryCode: '+7',
    alphaCode: 'RUS',
  ),
  SPhoneNumber(
    numCode: '646',
    isoCode: 'RW',
    countryName: 'Rwanda',
    countryCode: '+250',
    alphaCode: 'RWA',
  ),
  SPhoneNumber(
    numCode: '652',
    isoCode: 'BL',
    countryName: 'Saint Barthélemy',
    countryCode: '+590',
    alphaCode: 'BLM',
  ),
  SPhoneNumber(
    numCode: '654',
    isoCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    countryCode: '+290',
    alphaCode: 'SHN',
  ),
  SPhoneNumber(
    numCode: '659',
    isoCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    countryCode: '+1869',
    alphaCode: 'KNA',
  ),
  SPhoneNumber(
    numCode: '662',
    isoCode: 'LC',
    countryName: 'Saint Lucia',
    countryCode: '+1758',
    alphaCode: 'LCA',
  ),
  SPhoneNumber(
    numCode: '663',
    isoCode: 'MF',
    countryName: 'Saint Martin (French part)',
    countryCode: '+590',
    alphaCode: 'MAF',
  ),
  SPhoneNumber(
    numCode: '666',
    isoCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    countryCode: '+508',
    alphaCode: 'SPM',
  ),
  SPhoneNumber(
    numCode: '670',
    isoCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    countryCode: '+1784',
    alphaCode: 'VCT',
  ),
  SPhoneNumber(
    numCode: '882',
    isoCode: 'WS',
    countryName: 'Samoa',
    countryCode: '+685',
    alphaCode: 'WSM',
  ),
  SPhoneNumber(
    numCode: '674',
    isoCode: 'SM',
    countryName: 'San Marino',
    countryCode: '+378',
    alphaCode: 'SMR',
  ),
  SPhoneNumber(
    numCode: '678',
    isoCode: 'ST',
    countryName: 'Sao Tome and Principe',
    countryCode: '+239',
    alphaCode: 'STP',
  ),
  SPhoneNumber(
    numCode: '682',
    isoCode: 'SA',
    countryName: 'Saudi Arabia',
    countryCode: '+966',
    alphaCode: 'SAU',
  ),
  SPhoneNumber(
    numCode: '686',
    isoCode: 'SN',
    countryName: 'Senegal',
    countryCode: '+221',
    alphaCode: 'SEN',
  ),
  SPhoneNumber(
    numCode: '688',
    isoCode: 'RS',
    countryName: 'Serbia',
    countryCode: '+381',
    alphaCode: 'SRB',
  ),
  SPhoneNumber(
    numCode: '690',
    isoCode: 'SC',
    countryName: 'Seychelles',
    countryCode: '+248',
    alphaCode: 'SYC',
  ),
  SPhoneNumber(
    numCode: '694',
    isoCode: 'SL',
    countryName: 'Sierra Leone',
    countryCode: '+232',
    alphaCode: 'SLE',
  ),
  SPhoneNumber(
    numCode: '702',
    isoCode: 'SG',
    countryName: 'Singapore',
    countryCode: '+65',
    alphaCode: 'SGP',
  ),
  SPhoneNumber(
    numCode: '703',
    isoCode: 'SK',
    countryName: 'Slovakia',
    countryCode: '+421',
    alphaCode: 'SVK',
  ),
  SPhoneNumber(
    numCode: '705',
    isoCode: 'SI',
    countryName: 'Slovenia',
    countryCode: '+386',
    alphaCode: 'SVN',
  ),
  SPhoneNumber(
    numCode: '90',
    isoCode: 'SB',
    countryName: 'Solomon Islands',
    countryCode: '+677',
    alphaCode: 'SLB',
  ),
  SPhoneNumber(
    numCode: '706',
    isoCode: 'SO',
    countryName: 'Somalia',
    countryCode: '+252',
    alphaCode: 'SOM',
  ),
  SPhoneNumber(
    numCode: '710',
    isoCode: 'ZA',
    countryName: 'South Africa',
    countryCode: '+27',
    alphaCode: 'ZAF',
  ),
  SPhoneNumber(
    numCode: '239',
    isoCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    countryCode: '+500',
    alphaCode: 'SGS',
  ),
  SPhoneNumber(
    numCode: '728',
    isoCode: 'SS',
    countryName: 'South Sudan',
    countryCode: '+211',
    alphaCode: 'SSD',
  ),
  SPhoneNumber(
    numCode: '724',
    isoCode: 'ES',
    countryName: 'Spain',
    countryCode: '+34',
    alphaCode: 'ESP',
  ),
  SPhoneNumber(
    numCode: '144',
    isoCode: 'LK',
    countryName: 'Sri Lanka',
    countryCode: '+94',
    alphaCode: 'LKA',
  ),
  SPhoneNumber(
    numCode: '729',
    isoCode: 'SD',
    countryName: 'Sudan',
    countryCode: '+249',
    alphaCode: 'SDN',
  ),
  SPhoneNumber(
    numCode: '740',
    isoCode: 'SR',
    countryName: 'Suriname',
    countryCode: '+597',
    alphaCode: 'SUR',
  ),
  SPhoneNumber(
    numCode: '744',
    isoCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    countryCode: '+47',
    alphaCode: 'SJM',
  ),
  SPhoneNumber(
    numCode: '748',
    isoCode: 'SZ',
    countryName: 'Swaziland',
    countryCode: '+268',
    alphaCode: 'SWZ',
  ),
  SPhoneNumber(
    numCode: '752',
    isoCode: 'SE',
    countryName: 'Sweden',
    countryCode: '+46',
    alphaCode: 'SWE',
  ),
  SPhoneNumber(
    numCode: '756',
    isoCode: 'CH',
    countryName: 'Switzerland',
    countryCode: '+41',
    alphaCode: 'CHE',
  ),
  SPhoneNumber(
    numCode: '760',
    isoCode: 'SY',
    countryName: 'Syrian Arab Republic',
    countryCode: '+963',
    alphaCode: 'SYR',
  ),
  SPhoneNumber(
    numCode: '158',
    isoCode: 'TW',
    countryName: 'Taiwan',
    countryCode: '+886',
    alphaCode: 'TWN',
  ),
  SPhoneNumber(
    numCode: '762',
    isoCode: 'TJ',
    countryName: 'Tajikistan',
    countryCode: '+992',
    alphaCode: 'TJK',
  ),
  SPhoneNumber(
    numCode: '834',
    isoCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    countryCode: '+255',
    alphaCode: 'TZA',
  ),
  SPhoneNumber(
    numCode: '764',
    isoCode: 'TH',
    countryName: 'Thailand',
    countryCode: '+66',
    alphaCode: 'THA',
  ),
  SPhoneNumber(
    numCode: '626',
    isoCode: 'TL',
    countryName: 'Timor-Leste',
    countryCode: '+670',
    alphaCode: 'TLS',
  ),
  SPhoneNumber(
    numCode: '768',
    isoCode: 'TG',
    countryName: 'Togo',
    countryCode: '+228',
    alphaCode: 'TGO',
  ),
  SPhoneNumber(
    numCode: '772',
    isoCode: 'TK',
    countryName: 'Tokelau',
    countryCode: '+690',
    alphaCode: 'TKL',
  ),
  SPhoneNumber(
    numCode: '776',
    isoCode: 'TO',
    countryName: 'Tonga',
    countryCode: '+676',
    alphaCode: 'TON',
  ),
  SPhoneNumber(
    numCode: '780',
    isoCode: 'TT',
    countryName: 'Trinidad and Tobago',
    countryCode: '+1868',
    alphaCode: 'TTO',
  ),
  SPhoneNumber(
    numCode: '788',
    isoCode: 'TN',
    countryName: 'Tunisia',
    countryCode: '+216',
    alphaCode: 'TUN',
  ),
  SPhoneNumber(
    numCode: '792',
    isoCode: 'TR',
    countryName: 'Turkey',
    countryCode: '+90',
    alphaCode: 'TUR',
  ),
  SPhoneNumber(
    numCode: '795',
    isoCode: 'TM',
    countryName: 'Turkmenistan',
    countryCode: '+993',
    alphaCode: 'TKM',
  ),
  SPhoneNumber(
    numCode: '796',
    isoCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    countryCode: '+1649',
    alphaCode: 'TCA',
  ),
  SPhoneNumber(
    numCode: '798',
    isoCode: 'TV',
    countryName: 'Tuvalu',
    countryCode: '+688',
    alphaCode: 'TUV',
  ),
  SPhoneNumber(
    numCode: '800',
    isoCode: 'UG',
    countryName: 'Uganda',
    countryCode: '+256',
    alphaCode: 'UGA',
  ),
  SPhoneNumber(
    numCode: '804',
    isoCode: 'UA',
    countryName: 'Ukraine',
    countryCode: '+380',
    alphaCode: 'UKR',
  ),
  SPhoneNumber(
    numCode: '784',
    isoCode: 'AE',
    countryName: 'United Arab Emirates',
    countryCode: '+971',
    alphaCode: 'ARE',
  ),
  SPhoneNumber(
    numCode: '826',
    isoCode: 'GB',
    countryName: 'United Kingdom of Great Britain and Northern Ireland',
    countryCode: '+44',
    alphaCode: 'GBR',
  ),
  SPhoneNumber(
    numCode: '840',
    isoCode: 'US',
    countryName: 'United States of America',
    countryCode: '+1',
    alphaCode: 'USA',
  ),
  SPhoneNumber(
    numCode: '858',
    isoCode: 'UY',
    countryName: 'Uruguay',
    countryCode: '+598',
    alphaCode: 'URY',
  ),
  SPhoneNumber(
    numCode: '860',
    isoCode: 'UZ',
    countryName: 'Uzbekistan',
    countryCode: '+998',
    alphaCode: 'UZB',
  ),
  SPhoneNumber(
    numCode: '548',
    isoCode: 'VU',
    countryName: 'Vanuatu',
    countryCode: '+678',
    alphaCode: 'VUT',
  ),
  SPhoneNumber(
    numCode: '862',
    isoCode: 'VE',
    countryName: 'Venezuela (Bolivarian Republic of)',
    countryCode: '+58',
    alphaCode: 'VEN',
  ),
  SPhoneNumber(
    numCode: '704',
    isoCode: 'VN',
    countryName: 'Vietnam',
    countryCode: '+84',
    alphaCode: 'VNM',
  ),
  SPhoneNumber(
    numCode: '92',
    isoCode: 'VG',
    countryName: 'Virgin Islands (British)',
    countryCode: '+1284',
    alphaCode: 'VGB',
  ),
  SPhoneNumber(
    numCode: '850',
    isoCode: 'VI',
    countryName: 'Virgin Islands (U.S.)',
    countryCode: '+1340',
    alphaCode: 'VIR',
  ),
  SPhoneNumber(
    numCode: '876',
    isoCode: 'WF',
    countryName: 'Wallis and Futuna',
    countryCode: '+681',
    alphaCode: 'WLF',
  ),
  SPhoneNumber(
    numCode: '887',
    isoCode: 'YE',
    countryName: 'Yemen',
    countryCode: '+967',
    alphaCode: 'YEM',
  ),
  SPhoneNumber(
    numCode: '894',
    isoCode: 'ZM',
    countryName: 'Zambia',
    countryCode: '+260',
    alphaCode: 'ZMB',
  ),
  SPhoneNumber(
    numCode: '716',
    isoCode: 'ZW',
    countryName: 'Zimbabwe',
    countryCode: '+263',
    alphaCode: 'ZWE',
  ),
];
