import 'package:flutter/material.dart';

abstract class SimpleColors {
  abstract Color red;
  abstract Color blue;
  abstract Color blue2;
  abstract Color green;
  abstract Color seaGreen;
  abstract Color leafGreen;
  abstract Color aquaGreen;
  abstract Color orange;
  abstract Color brown;
  abstract Color darkBrown;
  abstract Color grey1;
  abstract Color grey2;
  abstract Color grey3;
  abstract Color grey4;
  abstract Color grey5;
  abstract Color grey6;
  abstract Color black;
  abstract Color white;
  abstract Color violet;
  abstract Color redLight;
  abstract Color blueLight;
  abstract Color extraGreenLight;
  abstract Color greenLight;
  abstract Color greenDarkLight;
  abstract Color yellowLight;
  abstract Color yellowDarkLight;
  abstract Color brownLight;
  abstract Color violetLight;
  abstract Color greenLight2;
  abstract Color blueLight2;
  abstract Color confetti1;
  abstract Color confetti2;
  abstract Color confetti3;
  abstract Color confetti4;
  abstract Color confetti5;
  abstract Color confetti6;
  abstract Color confetti7;
  abstract Color confetti8;
  abstract Color purple;
}
