// ignore_for_file: directives_ordering

library simple_kit;

export 'core/simple_kit.dart' show sKit;

/// Actions
export 'modules/actions/confirm_action_timer/simple_confirm_action_timer.dart';
export 'modules/actions/confirm_action_timer/simple_confirm_action_timer_painter.dart';
export 'modules/actions/confirm_action_timer/simple_timer_animation_countdown.dart';

/// Agreements
export 'modules/agreements/simple_privacy_policy/simple_policy_checkbox.dart';
export 'modules/agreements/simple_privacy_policy/simple_policy_text.dart';

/// Buttons
export 'modules/buttons/basic_buttons/primary_button/public/simple_primary_button_1.dart';
export 'modules/buttons/basic_buttons/primary_button/public/simple_primary_button_2.dart';
export 'modules/buttons/basic_buttons/primary_button/public/simple_primary_button_3.dart';
export 'modules/buttons/basic_buttons/secondary_button/public/simple_secondary_button_1.dart';
export 'modules/buttons/basic_buttons/secondary_button/public/simple_secondary_button_2.dart';
export 'modules/buttons/basic_buttons/text_button/public/simple_text_button_1.dart';
export 'modules/buttons/basic_buttons/text_button/public/simple_text_button_2.dart';
export 'modules/buttons/resend_button/simple_resend_button.dart';
export 'modules/buttons/simple_floating_button_frame.dart';
export 'modules/buttons/simple_floating_button_frame2.dart';
export 'modules/buttons/simple_circle_icon_button.dart';
export 'modules/buttons/simple_icon_text_button.dart';

/// Colors
export 'modules/colors/simple_colors.dart';

/// Fields
export 'modules/fields/standard_field/base/standard_field_error_notifier.dart';
export 'modules/fields/standard_field/public/simple_standard_field.dart';
export 'modules/fields/standard_field/public/simple_standard_field_obscure.dart';

/// Icons
export 'modules/icons/102x56/public/numeric_keyboard_erase/simple_numeric_keyboard_erase_icon.dart';
export 'modules/icons/102x56/public/numeric_keyboard_erase/simple_numeric_keyboard_erase_pressed_icon.dart';
export 'modules/icons/102x56/public/numeric_keyboard_face_id/simple_numeric_keyboard_face_id_icon.dart';
export 'modules/icons/102x56/public/numeric_keyboard_face_id/simple_numeric_keyboard_face_id_pressed_icon.dart';
export 'modules/icons/102x56/public/numeric_keyboard_fingerprint/simple_numeric_keyboard_fingerprint_icon.dart';
export 'modules/icons/102x56/public/numeric_keyboard_fingerprint/simple_numeric_keyboard_fingerprint_pressed_icon.dart';
export 'modules/icons/16x16/public/close/simple_close_icon.dart';
export 'modules/icons/16x16/public/tick/simple_tick_icon.dart';
export 'modules/icons/16x16/public/tick/simple_tick_selected_icon.dart';
export 'modules/icons/20x20/public/minus/simple_minus_icon.dart';
export 'modules/icons/20x20/public/list_checkmark/simple_minus_list_icon.dart';
export 'modules/icons/20x20/public/list_checkmark/simple_check_list_icon.dart';
export 'modules/icons/20x20/public/plus/simple_plus_icon.dart';
export 'modules/icons/20x20/public/receive_by_phone/simple_receive_by_phone_icon.dart';
export 'modules/icons/20x20/public/send_by_phone/simple_send_by_phone_icon.dart';
export 'modules/icons/20x20/public/swap/simple_swap_icon.dart';
export 'modules/icons/20x20/public/withdrawal_fee/simple_withdrawal_fee_icon.dart';
export 'modules/icons/20x20/public/circle_minus/simple_circle_minus_icon.dart';
export 'modules/icons/20x20/public/bank/simple_bank_icon.dart';
export 'modules/icons/20x20/public/user/simple_user_icon.dart';
export 'modules/icons/20x20/public/rewards/simple_reward_icon.dart';
export 'modules/icons/20x20/public/cash/simple_cash_icon.dart';
export 'modules/icons/20x20/public/simple_card_actions/simple_card_settings_icon.dart';
export 'modules/icons/20x20/public/simple_card_actions/simple_freeze_icon.dart';
export 'modules/icons/20x20/public/simple_card_actions/simple_hide_details_icon.dart';
export 'modules/icons/20x20/public/simple_card_actions/simple_show_details_icon.dart';
export 'modules/icons/20x20/public/simple_card_actions/simple_terminate_icon.dart';
export 'modules/icons/24x24/public/about_us/simple_about_us_icon.dart';
export 'modules/icons/24x24/public/account_status/simple_account_verify_icon.dart';
export 'modules/icons/24x24/public/account_status/simple_account_waiting_icon.dart';
export 'modules/icons/24x24/public/account_status/simple_account_blocked_icon.dart';
export 'modules/icons/24x24/public/action_buy/simple_action_buy_icon.dart';
export 'modules/icons/24x24/public/action_convert/simple_action_convert_icon.dart';
export 'modules/icons/24x24/public/action_deposit/simple_action_deposit_icon.dart';
export 'modules/icons/24x24/public/action_receive/simple_action_receive_icon.dart';
export 'modules/icons/24x24/public/action_sell/simple_action_sell_icon.dart';
export 'modules/icons/24x24/public/action_send/simple_action_send_icon.dart';
export 'modules/icons/24x24/public/action_withdraw/simple_action_withdraw_icon.dart';
export 'modules/icons/24x24/public/adv_cash/simple_adv_cash_icon.dart';
export 'modules/icons/24x24/public/angle_down/simple_angle_down_icon.dart';
export 'modules/icons/24x24/public/angle_down/simple_angle_down_pressed_icon.dart';
export 'modules/icons/24x24/public/angle_up/simple_angle_up_icon.dart';
export 'modules/icons/24x24/public/angle_up/simple_angle_up_pressed_icon.dart';
export 'modules/icons/24x24/public/asset_placeholder/simple_asset_placeholder_icon.dart';
export 'modules/icons/24x24/public/back/simple_back_icon.dart';
export 'modules/icons/24x24/public/back/simple_back_pressed_icon.dart';
export 'modules/icons/24x24/public/big_arrow/simple_arrow_up_icon.dart';
export 'modules/icons/24x24/public/big_arrow/simple_big_arrow_negative_icon.dart';
export 'modules/icons/24x24/public/big_arrow/simple_big_arrow_positive_icon.dart';
export 'modules/icons/24x24/public/blue_right_arrow/simple_blue_right_arrow_icon.dart';
export 'modules/icons/24x24/public/change_pin/simple_change_pin_icon.dart';
export 'modules/icons/24x24/public/checkbox/simple_checkbox_icon.dart';
export 'modules/icons/24x24/public/checkbox/simple_checkbox_selected_icon.dart';
export 'modules/icons/24x24/public/close/simple_close_icon.dart';
export 'modules/icons/24x24/public/close/simple_close_pressed_icon.dart';
export 'modules/icons/24x24/public/close/simple_close_with_border_icon.dart';
export 'modules/icons/24x24/public/complete/simple_complete_icon.dart';
export 'modules/icons/24x24/public/complete/simple_complete_done_icon.dart';
export 'modules/icons/24x24/public/copy/simple_copy_icon.dart';
export 'modules/icons/24x24/public/copy/simple_copy_pressed_icon.dart';
export 'modules/icons/24x24/public/delete/simple_delete_manage_icon.dart';
export 'modules/icons/24x24/public/erase/simple_erase_icon.dart';
export 'modules/icons/24x24/public/erase/simple_erase_market_icon.dart';
export 'modules/icons/24x24/public/erase/simple_erase_pressed_icon.dart';
export 'modules/icons/24x24/public/earn/simple_earn_withdrawal_icon.dart';
export 'modules/icons/24x24/public/edit/simple_edit_icon.dart';
export 'modules/icons/24x24/public/done/simple_done_icon.dart';
export 'modules/icons/24x24/public/done/simple_blue_done_icon.dart';
export 'modules/icons/24x24/public/error/simple_error_icon.dart';
export 'modules/icons/24x24/public/error/simple_error_pressed_icon.dart';
export 'modules/icons/24x24/public/eye_close/simple_eye_close_icon.dart';
export 'modules/icons/24x24/public/eye_close/simple_eye_close_pressed_icon.dart';
export 'modules/icons/24x24/public/eye_open/simple_eye_open_icon.dart';
export 'modules/icons/24x24/public/eye_open/simple_eye_open_pressed_icon.dart';
export 'modules/icons/24x24/public/faq/simple_faq_icon.dart';
export 'modules/icons/24x24/public/top_up/simple_top_up_icon.dart';
export 'modules/icons/24x24/public/forward/simple_forward_icon.dart';
export 'modules/icons/24x24/public/gift/simple_gift_icon.dart';
export 'modules/icons/24x24/public/gift/simple_gift_pressed_icon.dart';
export 'modules/icons/24x24/public/gift_portfolio/simple_gift_portfolio_icon.dart';
export 'modules/icons/24x24/public/refund/simple_refund_icon.dart';
export 'modules/icons/24x24/public/purchase/simple_purchase_icon.dart';
export 'modules/icons/24x24/public/index_history/simple_index_history_icon.dart';
export 'modules/icons/24x24/public/info/simple_info_icon.dart';
export 'modules/icons/24x24/public/info/simple_info_pressed_icon.dart';
export 'modules/icons/24x24/public/invite_friends/simple_invite_friends_icon.dart';
export 'modules/icons/24x24/public/kyc/simple_document_icon.dart';
export 'modules/icons/24x24/public/kyc/simple_passport_icon.dart';
export 'modules/icons/24x24/public/kyc/simple_resident_icon.dart';
export 'modules/icons/24x24/public/kyc/simple_driver_license_icon.dart';
export 'modules/icons/24x24/public/lock/simple_lock_icon.dart';
export 'modules/icons/24x24/public/log_out/simple_log_out_icon.dart';
export 'modules/icons/24x24/public/mail/simple_mail_icon.dart';
export 'modules/icons/24x24/public/mail/simple_mail_pressed_icon.dart';
export 'modules/icons/24x24/public/mail/simple_mail2_icon.dart';
export 'modules/icons/24x24/public/notifications/simple_notifications_icon.dart';
export 'modules/icons/24x24/public/paste/simple_paste_icon.dart';
export 'modules/icons/24x24/public/paste/simple_paste_pressed_icon.dart';
export 'modules/icons/24x24/public/pause/simple_pause_icon.dart';
export 'modules/icons/24x24/public/paused/simple_paused_icon.dart';
export 'modules/icons/24x24/public/persona/simple_selfie_icon.dart';
export 'modules/icons/24x24/public/phone_call/simple_phone_call_icon.dart';
export 'modules/icons/24x24/public/phone/simple_phone_icon.dart';
export 'modules/icons/24x24/public/photo/simple_photo_icon.dart';
export 'modules/icons/24x24/public/photo/simple_photo_pressed_icon.dart';
export 'modules/icons/24x24/public/photo/simple_white_photo_icon.dart';
export 'modules/icons/24x24/public/profile_details/simple_profile_details_icon.dart';
export 'modules/icons/24x24/public/qr_code/simple_qr_code_icon.dart';
export 'modules/icons/24x24/public/qr_code/simple_qr_code_pressed_icon.dart';
export 'modules/icons/24x24/public/question/simple_question_icon.dart';
export 'modules/icons/24x24/public/recurring_buys/simple_recurring_buys_icon.dart';
export 'modules/icons/24x24/public/search/simple_search_icon.dart';
export 'modules/icons/24x24/public/search/simple_search_pressed_icon.dart';
export 'modules/icons/24x24/public/security/simple_security_icon.dart';
export 'modules/icons/24x24/public/share/simple_share_icon.dart';
export 'modules/icons/24x24/public/star/simple_star_icon.dart';
export 'modules/icons/24x24/public/star/simple_star_pressed_icon.dart';
export 'modules/icons/24x24/public/star/simple_star_selected_icon.dart';
export 'modules/icons/24x24/public/support/simple_support_icon.dart';
export 'modules/icons/24x24/public/two_factor_auth/simple_two_factor_auth_icon.dart';
export 'modules/icons/24x24/public/wallet/simple_wallet_icon.dart';
export 'modules/icons/24x24/public/wire/simple_wire_icon.dart';
export 'modules/icons/24x24/public/network/simple_network_icon.dart';
export 'modules/icons/24x24/public/account/simple_account_icon.dart';
export 'modules/icons/24x24/public/rewards/simple_rewards_icon.dart';
export 'modules/icons/36x36/public/face_id/simple_face_id_icon.dart';
export 'modules/icons/36x36/public/face_id/simple_face_id_pressed_icon.dart';
export 'modules/icons/36x36/public/fingerprint/simple_fingerprint_icon.dart';
export 'modules/icons/36x36/public/fingerprint/simple_fingerprint_pressed_icon.dart';
export 'modules/icons/36x36/public/keyboard_erase/simple_keyboard_erase_icon.dart';
export 'modules/icons/36x36/public/keyboard_erase/simple_keyboard_erase_pressed_icon.dart';
export 'modules/icons/40x22/public/delete/simple_delete_icon.dart';
export 'modules/icons/40x40/public/convert/simple_convert_icon.dart';
export 'modules/icons/40x40/public/convert/simple_convert_pressed_icon.dart';
export 'modules/icons/56x56/public/action/simple_action_active_highlighted_icon.dart';
export 'modules/icons/56x56/public/action/simple_action_active_icon.dart';
export 'modules/icons/56x56/public/action/simple_action_default_icon.dart';
export 'modules/icons/56x56/public/market/simple_market_active_icon.dart';
export 'modules/icons/56x56/public/market/simple_market_default_icon.dart';
export 'modules/icons/56x56/public/news/simple_news_active_icon.dart';
export 'modules/icons/56x56/public/news/simple_news_default_icon.dart';
export 'modules/icons/56x56/public/earn/simple_earn_active_icon.dart';
export 'modules/icons/56x56/public/earn/simple_earn_default_icon.dart';
export 'modules/icons/56x56/public/portfolio/simple_portfolio_active_icon.dart';
export 'modules/icons/56x56/public/portfolio/simple_portfolio_default_icon.dart';
export 'modules/icons/56x56/public/profile/simple_profile_active_icon.dart';
export 'modules/icons/56x56/public/profile/simple_profile_default_icon.dart';
export 'modules/icons/custom/public/cards/simple_visa_card_icon.dart';
export 'modules/icons/custom/public/cards/simple_visa_card_big_icon.dart';
export 'modules/icons/custom/public/cards/simple_mastercard_icon.dart';
export 'modules/icons/custom/public/cards/simple_google_pay_icon.dart';
export 'modules/icons/custom/public/invest/simple_invest_arrow.dart';
export 'modules/icons/custom/public/invest/simple_invest_asset_placeholder.dart';
export 'modules/icons/custom/public/invest/simple_invest_buy.dart';
export 'modules/icons/custom/public/invest/simple_invest_chart_candles.dart';
export 'modules/icons/custom/public/invest/simple_invest_chart_line.dart';
export 'modules/icons/custom/public/invest/simple_invest_calendar.dart';
export 'modules/icons/custom/public/invest/simple_invest_check.dart';
export 'modules/icons/custom/public/invest/simple_invest_checked.dart';
export 'modules/icons/custom/public/invest/simple_invest_close.dart';
export 'modules/icons/custom/public/invest/simple_invest_edit.dart';
export 'modules/icons/custom/public/invest/simple_invest_plus.dart';
export 'modules/icons/custom/public/invest/simple_invest_profit_equal.dart';
export 'modules/icons/custom/public/invest/simple_invest_profit_loss.dart';
export 'modules/icons/custom/public/invest/simple_invest_profit_win.dart';
export 'modules/icons/custom/public/invest/simple_invest_report.dart';
export 'modules/icons/custom/public/invest/simple_invest_sell.dart';
export 'modules/icons/custom/public/invest/simple_invest_search.dart';
export 'modules/icons/custom/public/invest/simple_invest_setting.dart';
export 'modules/icons/custom/public/invest/simple_invest_sort_down.dart';
export 'modules/icons/custom/public/invest/simple_invest_sort_not_set.dart';
export 'modules/icons/custom/public/invest/simple_invest_sort_up.dart';
export 'modules/icons/custom/public/invest/simple_invest_share.dart';
export 'modules/icons/custom/public/invest/simple_invest_wallet.dart';
export 'modules/icons/custom/public/stars/simple_stars_icon.dart';
export 'modules/icons/custom/public/star/simple_star_icon.dart';
export 'modules/icons/custom/public/cards/simple_card.dart';
export 'modules/icons/custom/public/cards/simple_wallet_card.dart';
export 'modules/icons/custom/public/cards/simple_mastercard_big_icon.dart';
export 'modules/icons/custom/public/cards/simple_frozen_card_icon.dart';
export 'modules/icons/custom/public/cards/simple_frozen_icon.dart';
export 'modules/icons/24x24/public/gift/simple_gift_send_icon.dart';
export 'modules/icons/24x24/public/history_completed/simple_history_completed_icon.dart';
export 'modules/icons/24x24/public/history_declined/simple_history_declined_icon.dart';

/// Page Frames
export 'modules/shared/qr_code_fields/simple_address_field_with_copy.dart';

/// QR Code related
export 'modules/shared/qr_code_fields/simple_qr_code_box.dart';
export 'modules/shared/qr_code_fields/simple_skeleton_qr_loader.dart';

/// Components
export 'modules/shared/simple_baseline_child.dart';
export 'modules/shared/simple_clickable_link_text.dart';
export 'modules/shared/simple_field_divider_frame.dart';
export 'modules/shared/simple_paddings.dart';
export 'modules/shared/simple_requirement.dart';
export 'modules/shared/simple_show_alert_popup.dart';
export 'modules/shared/simple_skeleton_text_loader.dart';
export 'modules/shared/simple_spacers.dart';
export 'modules/shared/simple_transparent_ink_well.dart';

/// Helpers
export 'helpers/biometrics_auth_helpers.dart';
export 'helpers/validators/validator.dart';
export 'helpers/validators/latin_validator.dart';

/// Utils
export 'utils/constants.dart';
export 'utils/enum.dart';

/// Texts
export 'modules/texts/simple_text_styles.dart';

/// Theme
export 'modules/theme/simple_theme.dart';
