name: iOS CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v1
        with:
          java-version: "16.x"
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.0

#       - name: Set up keychain
#         run: |
#           security create-keychain -p "test123" my.keychain
#           security default-keychain -s my.keychain
#           security unlock-keychain -p "test123" my.keychain

#       - name: Fetch signing files
#         run: |
#           app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
#         env:
#           PATH: ${{ env.PATH }}:/usr/local/bin

#       - name: Use system default keychain
#         run: |
#           security find-identity -v -p codesigning
#           security list-keychains
#           security import ./certificate.p12 -P "test123" -A
#           security set-key-partition-list -S apple-tool:,apple: -s -k "test123" my.keychain
#           security set-keychain-settings my.keychain

#       - name: Set up code signing settings on Xcode project
#         run: |
#           xcode-project use-profiles

      - name: Add GoogleService-Info.plist
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_IOS_STAGE }} | base64 --decode > ./ios/Runner/GoogleService-Info.plist

      - name: ls -la
        run: ls -la
        
      - name: Clean Flutter project
        run: flutter clean

      - name: Get Flutter packages
        run: flutter pub get
        
      - name: Build iOS app
        run: |
          flutter build ipa --release --target=lib/main_stage.dart --flavor=stage \
            --build-name=$(git ls-remote --tags origin | tail -1 | cut -d/ -f3) \
            --build-number=$GITHUB_RUN_NUMBER \
            --dart-define=MY_APP_ENV=prod \
            --export-options-plist=/Users/builder/export_options.plist \
            -allowProvisioningUpdates
            
  
