name: iOS CI/CD

on:
  push:

jobs:
  build_and_publish:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up keychain
        run: |
          security create-keychain -p "test123" my.keychain
          security default-keychain -s my.keychain
          security unlock-keychain -p "test123" my.keychain

      - name: Fetch signing files
        run: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Use system default keychain
        run: |
          security find-identity -v -p codesigning
          security list-keychains
          security import ./certificate.p12 -P "password" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "password" my.keychain
          security set-keychain-settings my.keychain

      - name: Set up code signing settings on Xcode project
        run: |
          xcode-project use-profiles

      - name: Add GoogleService-Info.plist
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_IOS_STAGE }} | base64 --decode > ./ios/Runner/GoogleService-Info.plist

      - name: Clean Flutter project
        run: flutter clean

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build iOS app
        run: |
          flutter build ipa --release --target=lib/main_stage.dart --flavor=stage \
            --build-name=$(git ls-remote --tags origin | tail -1 | cut -d/ -f3) \
            --build-number=$PROJECT_BUILD_NUMBER \
            --dart-define=MY_APP_ENV=prod \
            --export-options-plist=/Users/builder/export_options.plist
