name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]

jobs:
  flutter_test:
    name: Test, build and release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: echo ${{ secrets.FIREBASE_TEST }} | base64 --decode > ./android/app/google-services.json
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: cd plugins/simple_networking ; flutter pub get ; flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter test
      - run: |
          sed -i 's/version: 1.0.0+1/version: 1.0.0+${{ github.run_number }}/' ./pubspec.yaml
          cat ./pubspec.yaml

      # - name: Check Service dir
      #   run: |
      #     pwd
      #     ls
      #     echo "hello"

      # - name: Publish image
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: ${{ secrets.ORG_NAME }}/flutter.jetwallet/myjetwallet.flutter.jetwallet-test
      #     tags: latest
          
      # - name: Publish image ST
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.ST_DOCKER_USER }}
      #     password: ${{ secrets.ST_DOCKER_PASSWORD }}
      #     registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      #     repository: spot/myjetwallet.flutter.jetwallet-test
      #     tags: latest             

  # restart:
  #   runs-on: self-hosted    
  #   needs: flutter_test
  #   steps:
  #   - name: Restart service
  #     uses: Myjetwallet/kube-restart-pods@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA__ST_TEST }}
  #       NAMESPACE: ${{ secrets.KUBE_TEST_NAMESPACE }}
  #       POD: flutter-app
