name: Flutter pull request

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ master, develop ]

jobs:
  flutter_run_web:
    name: Test, build and release docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: echo ${{ secrets.FIREBASE_TEST }} | base64 --decode > ./android/app/google-services.json
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: cd plugins/simple_networking ; flutter pub get ; flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter test
      # - run: flutter build apk -t lib/main_production.dart --flavor prod --build-number=${{ github.run_number }}
