name: Flutter pull request

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  flutter_run_web:
    name: Test, build and release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: dart --version
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub cache repair
      - run: flutter pub upgrade
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter test
      - run: flutter build web --release --no-sound-null-safety
      - run: flutter build apk --build-number=${{ github.run_number }} --no-sound-null-safety
