name: Telegram notification

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            MERGED to branch <b>develop</b> PR: <b>${{ steps.extract_branch.outputs.branch }}</b>
